import type { ScheduleContent } from './types';

const schedule: ScheduleContent = {
	id: '2255',
	title: '2-2-5-5 Custody Schedule',
	slug: '2-2-5-5-custody-schedule',
	description: 'Preview a 2-2-5-5 custody schedule and understand how the two-week parenting rotation works.',
	metaTitle: '2-2-5-5 Custody Schedule | Calendar Examples & Tips',
	metaDescription: 'See how a 2-2-5-5 custody schedule works, view calendar examples, compare pros and cons, and calculate parenting time.',
	canonicalUrl: 'https://custodybuilder.com/2-2-5-5-custody-schedule/',
	lastUpdated: '2026-06-13',
	lede: 'A 2-2-5-5 custody schedule is a two-week parenting rotation where the child spends 2 days with Parent A, 2 days with Parent B, then 5 days with Parent A and 5 days with Parent B. It is often used by families who want stable weekdays, alternating weekends, and a balanced 50/50 custody schedule.',
	trust: {
		reviewerLabel: 'Reviewed for clarity by',
		reviewerName: 'CustodyBuilder Editorial Team',
		reviewerCredential: 'Reviewed for clarity, schedule mechanics, and practical usefulness by the CustodyBuilder Editorial Team.',
		reviewerHref: '/about/',
		authorName: 'CustodyBuilder Editorial Team',
		authorTitle: 'Parenting time calendar and custody schedule planning team',
		authorBio: 'CustodyBuilder creates plain-English custody schedule guides and calendar tools for parents comparing parenting time, printable schedules, and parenting plan language.',
		authorHref: '/about/',
		factCheckedDate: '2026-06-13',
		legalReviewerPlaceholder: 'Not yet reviewed by an attorney. This page is for educational planning only and should not be treated as legal advice.',
		disclaimer: 'This tool is for educational planning only and is not legal advice. Custody laws vary by state. Consult a qualified family law attorney or mediator for legal guidance.',
	},
	hero: {
		definition: 'A 2-2-5-5 custody schedule gives one parent two fixed weekdays, the other parent two fixed weekdays, then alternates five-day blocks that include weekends.',
		bestFor: 'families who want a 50/50 custody schedule with predictable school-week routines and fewer exchanges than 2-2-3.',
		proChips: ['Usually 50/50', 'Stable weekdays', 'Alternating weekends', 'Good for school-age children'],
		conChips: ['Five-day gaps', 'Needs activity planning', 'Midweek exchanges', 'Harder with long distance'],
		ctas: [
			{ text: 'Generate my 2-2-5-5 calendar', href: '#schedule-generator', variant: 'primary' },
			{ text: 'Download printable schedule', href: '#printable-download', variant: 'secondary' },
			{ text: 'Compare custody schedules', href: '#comparison', variant: 'secondary' },
		],
	},
	atAGlanceTitle: '2-2-5-5 Custody Schedule Summary',
	atAGlance: [
		{ label: 'Parenting time', value: 'Usually 50/50' },
		{ label: 'Rotation length', value: 'Two-week cycle' },
		{ label: 'Exchanges per week', value: 'Lower than 2-2-3' },
		{ label: 'Best for', value: 'School-age children' },
		{ label: 'Weekend pattern', value: 'Consistent' },
		{ label: 'Typical challenge', value: 'Longer stretches away from one parent' },
		{ label: 'Common use', value: 'Equal parenting plans' },
	],
	overview: [
		'The 2-2-5-5 custody schedule is popular because each parent can keep the same two weekdays every week while the longer five-day blocks alternate. For example, Parent A may consistently have Monday and Tuesday, Parent B may consistently have Wednesday and Thursday, and weekends rotate through the five-day blocks.',
		'Families often choose this schedule when school routines matter and both parents can manage predictable weekday exchanges. It gives children regular contact with both homes while reducing some of the exchange frequency found in a <a href="/2-2-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-3 custody schedule</a>.',
		'Use the <a href="/custody-schedule-generator/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">custody schedule generator</a> to test the rotation, then compare it with other <a href="/50-50-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">50/50 custody schedules</a> before adding terms to a parenting plan.',
	],
	printableDownload: {
		title: 'Printable 2-2-5-5 Custody Schedule Downloads',
		description: 'Use the generator above to print or export a 2-2-5-5 custody calendar. These resources are educational planning aids and should be reviewed before being used in a parenting plan.',
		options: [
			{
				title: 'Printable weekly schedule',
				description: 'Review the two-week 2-2-5-5 rhythm with fixed weekdays and alternating longer blocks.',
				status: 'available',
				href: '#timeline',
			},
			{
				title: 'Printable monthly calendar',
				description: 'Use the generator above to print or export a monthly custody calendar with parent labels and overnight totals.',
				status: 'available',
				href: '#schedule-generator',
			},
			{
				title: 'Yearly calendar',
				description: 'Use the generator above to export a yearly PDF after setting the start date and parent names.',
				status: 'available',
				href: '#schedule-generator',
			},
			{
				title: 'Parenting plan worksheet',
				description: 'Use the sample clause below as an educational starting point before professional review.',
				status: 'available',
				href: '#parenting-plan-language',
			},
			{
				title: 'Holiday planning worksheet',
				description: 'Use the holiday custody planner to organize holidays, school breaks, birthdays, and vacations separately from the regular rotation.',
				status: 'available',
				href: '/holiday-custody-planner/',
			},
		],
		ctas: [
			{ text: 'Generate printable calendar', href: '#schedule-generator', variant: 'primary' },
			{ text: 'Export PDF from the tool', href: '#schedule-generator', variant: 'secondary' },
			{ text: 'Plan holidays separately', href: '/holiday-custody-planner/', variant: 'secondary' },
		],
		yearOptions: ['Printable weekly schedule', 'Monthly PDF', 'Yearly PDF', 'Holiday worksheet'],
	},
	timeline: {
		title: 'How the 2-2-5-5 Schedule Works',
		description: 'This printable two-week timeline shows the common 2-2-5-5 pattern before holidays, vacations, or special-day overrides are added.',
		weeks: [
			{
				label: 'Week 1',
				blocks: [
					{ parent: 'Parent A', days: 'Mon Tue' },
					{ parent: 'Parent B', days: 'Wed Thu' },
					{ parent: 'Parent A', days: 'Fri Sat Sun Mon Tue' },
				],
			},
			{
				label: 'Week 2',
				blocks: [
					{ parent: 'Parent A', days: 'Wed Thu' },
					{ parent: 'Parent B', days: 'Fri Sat Sun Mon Tue' },
				],
			},
		],
	},
	parentingPlanLanguage: {
		title: 'Sample 2-2-5-5 Parenting Plan Language',
		description: 'This plain-English sample shows how the rotation can be described before it is adapted for a formal parenting plan.',
		clause: 'The parents will follow a repeating two-week 2-2-5-5 parenting schedule. Parent A will have parenting time every Monday and Tuesday. Parent B will have parenting time every Wednesday and Thursday. Weekend parenting time will alternate through the five-day blocks so that Parent A has parenting time from Friday after school or daycare through Wednesday exchange in one cycle, and Parent B has parenting time from Friday after school or daycare through Wednesday exchange in the next cycle. Holiday, school-break, vacation, birthday, Mother’s Day, Father’s Day, and special-day provisions will override the regular weekly schedule when they apply.',
		disclaimer: 'This sample is provided for educational purposes only and should be reviewed by a qualified family law professional before use.',
	},
	deepDiveSections: [
		{
			id: 'holidays-breaks-vacations',
			kicker: 'Special dates',
			title: 'Holidays, School Breaks, and Vacations',
			paragraphs: [
				'Holiday and vacation rules usually override the regular 2-2-5-5 rotation. Parents should write separate terms for Thanksgiving, Christmas, spring break, summer vacation, birthdays, Mother’s Day, Father’s Day, and other important family or cultural days.',
				'Many families alternate major holidays each year, split long school breaks, and give each parent a defined summer vacation block. After the override ends, the family usually returns to the regular 2-2-5-5 pattern unless the <a href="/parenting-plan-template/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">parenting plan template</a> says otherwise.',
			],
			items: [
				{ title: 'Thanksgiving and Christmas', description: 'Common approaches include alternating each holiday annually or splitting winter break into two blocks.' },
				{ title: 'Spring break and summer vacation', description: 'Parents often alternate spring break and reserve longer summer blocks with advance notice.' },
				{ title: 'Birthdays', description: 'Birthdays can follow the normal schedule, alternate yearly, or be shared by time of day.' },
				{ title: 'Mother’s Day and Father’s Day', description: 'Many plans assign these days to the named parent even when the regular rotation would say otherwise.' },
			],
		},
		{
			id: 'exchange-times-locations',
			kicker: 'Exchanges',
			title: 'Exchange Times and Locations',
			paragraphs: [
				'The 2-2-5-5 schedule works best when exchanges are predictable and low-conflict. Common exchange points include school, daycare, a public location, or an evening pickup time after work.',
				'School and daycare exchanges can reduce parent-to-parent contact, while public-location exchanges may help when home-to-home handoffs are stressful. Evening exchanges can work when both parents have stable work schedules, but they should not disrupt dinner, homework, or bedtime.',
			],
			items: [
				{ title: 'School exchanges', description: 'Pros: simple for school-age children and lower conflict. Cons: less useful during summer, holidays, or sick days.' },
				{ title: 'Daycare exchanges', description: 'Pros: predictable for younger children. Cons: parents need clear pickup authorization and backup plans.' },
				{ title: 'Public-location exchanges', description: 'Pros: useful for tense handoffs. Cons: adds travel time and may feel less natural for the child.' },
				{ title: 'Evening exchanges', description: 'Pros: works around jobs. Cons: can interfere with meals, homework, activities, and bedtime.' },
			],
		},
		{
			id: 'communication-tips',
			kicker: 'Co-parenting',
			title: 'Communication Tips for Parents Using a 2-2-5-5 Schedule',
			paragraphs: [
				'Because each parent keeps consistent weekdays, communication can be organized around school routines, activities, homework, medication, transportation, and upcoming schedule changes. A shared calendar helps both homes see when the five-day blocks begin and end.',
				'For planning conversations, use the <a href="/custody-percentage-calculator/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">custody percentage calculator</a> to review overnight totals and the <a href="/child-support-calculator/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">child support calculator</a> to understand support-planning questions that may come up before professional review.',
			],
			items: [
				{ title: 'Shared calendars', description: 'Track exchanges, school events, medical appointments, extracurricular activities, and holiday overrides in one place.' },
				{ title: 'Messaging apps', description: 'Keep messages child-focused and confirm changes in writing so both parents can refer back to the same details.' },
				{ title: 'Activity coordination', description: 'Assign who transports the child to practices, lessons, school events, appointments, and weekend activities.' },
				{ title: 'Schedule changes and documentation', description: 'Define notice deadlines, makeup-time rules, and how parents document agreed changes.' },
			],
		},
		{
			id: 'alternatives',
			kicker: 'Alternatives',
			title: 'Alternatives to 2-2-5-5',
			paragraphs: [
				'If 2-2-5-5 feels too long or too complicated, compare nearby options before finalizing a parenting plan. A <a href="/2-2-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-3 custody schedule</a> creates more frequent contact, while a <a href="/3-4-4-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">3-4-4-3 custody schedule</a> keeps equal time with fewer weekly changes.',
				'Older children may prefer a <a href="/week-on-week-off-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">week-on/week-off custody schedule</a>. If equal time is not realistic, compare <a href="/60-40-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">60/40</a>, <a href="/70-30-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">70/30</a>, <a href="/80-20-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">80/20</a>, or <a href="/every-other-weekend-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">every other weekend</a> schedules.',
			],
		},
	],
	pros: [
		'Stable weekdays for each parent',
		'Alternating weekends over the two-week cycle',
		'Balanced 50/50 parenting time',
		'Fewer exchanges than 2-2-3 for many families',
		'Easy to remember once each parent’s fixed weekdays are set',
	],
	cons: [
		'Five-day blocks may feel long for some younger children',
		'Midweek exchanges still require coordination',
		'School and activity logistics need to be planned carefully',
		'Can be difficult when parents live far apart',
		'One parent may miss several days of weekday routine during the longer block',
	],
	example: {
		title: '2-2-5-5 Schedule Example',
		description: 'In a common 2-2-5-5 schedule, Parent A has Monday and Tuesday, Parent B has Wednesday and Thursday, Parent A has Friday through Tuesday, and Parent B has Wednesday through Sunday. This creates stable weekdays and alternating weekends.',
		weeks: [
			{
				label: 'Week 1',
				blocks: [
					{ parent: 'Parent A', days: 'Mon Tue' },
					{ parent: 'Parent B', days: 'Wed Thu' },
					{ parent: 'Parent A', days: 'Fri Sat Sun' },
				],
			},
			{
				label: 'Week 2',
				blocks: [
					{ parent: 'Parent A', days: 'Mon Tue' },
					{ parent: 'Parent B', days: 'Wed Thu' },
					{ parent: 'Parent B', days: 'Fri Sat Sun' },
				],
			},
		],
	},
	comparison: {
		title: 'Compare 2-2-5-5 with other custody schedules',
		description: 'Use this table to compare the 2-2-5-5 schedule with other common custody calendar patterns before choosing a parenting plan schedule.',
		columnLabels: {
			schedule: 'Schedule',
			bestFor: 'Best age group',
			exchangeFrequency: 'Exchanges',
			weekendPattern: 'Stability',
			notes: 'Pros',
		},
		rows: [
			{
				schedule: '2-2-5-5',
				href: '/2-2-5-5-custody-schedule/',
				bestFor: 'School-age children who benefit from stable weekdays.',
				parentTimeSplit: 'Usually 50/50',
				exchangeFrequency: '2-3 exchanges per week',
				weekendPattern: 'High weekday stability',
				notes: 'Same weekdays, alternating weekends, fewer transitions than 2-2-3.',
				cons: 'Five-day stretches may feel long for some children.',
				guideLabel: 'Current guide',
				badge: 'Current page',
			},
			{
				schedule: '2-2-3',
				href: '/2-2-3-custody-schedule/',
				bestFor: 'Younger children who need frequent contact.',
				parentTimeSplit: 'Usually 50/50',
				exchangeFrequency: '3-4 exchanges per week',
				weekendPattern: 'Moderate stability',
				notes: 'Shorter gaps between parents and alternating weekends.',
				cons: 'More handoffs and more schedule coordination.',
				guideLabel: '2-2-3 guide',
			},
			{
				schedule: '3-4-4-3',
				href: '/3-4-4-3-custody-schedule/',
				bestFor: 'School-age children who can manage three- and four-day blocks.',
				parentTimeSplit: 'Usually 50/50',
				exchangeFrequency: '2 exchanges per week',
				weekendPattern: 'Moderate to high stability',
				notes: 'Fewer transitions while keeping regular contact.',
				cons: 'The pattern can be less intuitive at first.',
				guideLabel: '3-4-4-3 guide',
			},
			{
				schedule: 'Week-on/week-off',
				href: '/week-on-week-off-custody-schedule/',
				bestFor: 'Older children and teens.',
				parentTimeSplit: 'Usually 50/50',
				exchangeFrequency: '1 exchange per week',
				weekendPattern: 'High stability',
				notes: 'Simple calendar and fewer exchanges.',
				cons: 'A full week away may feel too long for some children.',
				guideLabel: 'Week-on/week-off guide',
			},
			{
				schedule: 'Every other weekend',
				href: '/every-other-weekend-custody-schedule/',
				bestFor: 'Families where one home anchors most school-week routines.',
				parentTimeSplit: 'Often 80/20 to 85/15',
				exchangeFrequency: 'Usually every other weekend',
				weekendPattern: 'High primary-home stability',
				notes: 'Simple and lower transition load.',
				cons: 'Much less routine weekday time for one parent.',
				guideLabel: 'Every other weekend guide',
			},
		],
		cta: {
			title: 'Compare other custody schedules',
			links: [
				{ title: '2-2-3 custody schedule', slug: '2-2-3-custody-schedule', description: 'Compare shorter blocks and more frequent parent contact.' },
				{ title: '3-4-4-3 custody schedule', slug: '3-4-4-3-custody-schedule', description: 'Review a 50/50 option with alternating three- and four-day blocks.' },
				{ title: 'Week on/week off custody schedule', slug: 'week-on-week-off-custody-schedule', description: 'See whether full weeks are easier for older children.' },
				{ title: 'Every other weekend schedule', slug: 'every-other-weekend-custody-schedule', description: 'Compare a lower-transition schedule when 50/50 is not realistic.' },
			],
		},
	},
	faq: [
		{
			question: 'What is a 2-2-5-5 custody schedule?',
			answer: 'A 2-2-5-5 custody schedule is a repeating two-week parenting plan with two short weekday blocks and two longer five-day blocks. It is commonly used as a 50/50 custody schedule because each parent receives equal time across the 14-day cycle.',
		},
		{
			question: 'Is 2-2-5-5 custody always 50/50?',
			answer: 'A standard 2-2-5-5 schedule is usually 50/50 because each parent receives seven overnights in a two-week cycle. Annual percentages can shift if holidays, vacations, school breaks, or special overrides change the regular pattern.',
		},
		{
			question: 'Is 2-2-5-5 better than 2-2-3?',
			answer: '2-2-5-5 may be better when school-week consistency and fewer exchanges matter more. 2-2-3 may be better when a child needs shorter gaps between parents and more frequent contact.',
			answerHtml: '2-2-5-5 may be better when school-week consistency and fewer exchanges matter more. A <a href="/2-2-3-custody-schedule/" class="text-accent hover:underline">2-2-3 custody schedule</a> may be better when a child needs shorter gaps between parents and more frequent contact.',
		},
		{
			question: 'Is 2-2-5-5 good for toddlers?',
			answer: 'It can work for some toddlers, but the five-day blocks may feel long if the child struggles with separation or needs very frequent contact. Parents should consider the toddler’s routine, attachment needs, exchange stress, and distance between homes.',
		},
		{
			question: 'Is 2-2-5-5 good for teenagers?',
			answer: 'It can work for teenagers when both homes can support school, transportation, activities, jobs, and social plans. Some teenagers prefer even fewer exchanges, so week-on/week-off may also be worth comparing.',
			answerHtml: 'It can work for teenagers when both homes can support school, transportation, activities, jobs, and social plans. Some teenagers prefer even fewer exchanges, so a <a href="/week-on-week-off-custody-schedule/" class="text-accent hover:underline">week-on/week-off custody schedule</a> may also be worth comparing.',
		},
		{
			question: 'What are the disadvantages of a 2-2-5-5 schedule?',
			answer: 'The main disadvantages are five-day stretches away from one parent, midweek exchanges that still require coordination, and possible difficulty when parents live far apart or a child has many activities.',
		},
		{
			question: 'How are holidays handled?',
			answer: 'Holidays usually override the regular 2-2-5-5 schedule. Parents should define major holidays, school breaks, birthdays, Mother’s Day, Father’s Day, and religious or cultural holidays separately in the parenting plan.',
			answerHtml: 'Holidays usually override the regular 2-2-5-5 schedule. Parents should define major holidays, school breaks, birthdays, Mother’s Day, Father’s Day, and religious or cultural holidays separately in the parenting plan. The <a href="/holiday-custody-planner/" class="text-accent hover:underline">holiday custody planner</a> can help organize those exceptions.',
		},
		{
			question: 'How are vacations handled?',
			answer: 'Vacation rules are usually written separately from the weekly rotation. Common terms include advance notice, maximum vacation length, travel details, makeup time, and whether vacation blocks override the normal schedule.',
		},
		{
			question: 'How many exchanges occur in a 2-2-5-5 schedule?',
			answer: 'Most 2-2-5-5 schedules have fewer exchanges than 2-2-3 because each parent keeps the same two weekdays and the weekend blocks are longer. The exact number depends on exchange times and how the calendar cycle is written.',
		},
		{
			question: 'Can this schedule affect child support?',
			answer: 'Parenting time can affect support discussions in some states, but child support rules vary. A 2-2-5-5 schedule is usually 50/50 by overnights, but income, expenses, state formulas, and court rules may still matter.',
			answerHtml: 'Parenting time can affect support discussions in some states, but child support rules vary. A 2-2-5-5 schedule is usually 50/50 by overnights, but income, expenses, state formulas, and court rules may still matter. Use the <a href="/child-support-calculator/" class="text-accent hover:underline">child support calculator</a> and <a href="/custody-percentage-calculator/" class="text-accent hover:underline">custody percentage calculator</a> as educational planning tools.',
		},
		{
			question: 'Can parents customize the schedule?',
			answer: 'Yes. Parents can adjust exchange times, exchange locations, holiday overrides, school-break rules, summer vacation blocks, and communication terms if their court order and local rules allow it.',
		},
		{
			question: 'How does 2-2-5-5 compare with alternating weeks?',
			answer: '2-2-5-5 gives more frequent contact and stable weekdays, while alternating weeks has fewer exchanges and simpler weekly blocks. Alternating weeks may work better for older children who can handle a full week in each home.',
			answerHtml: '2-2-5-5 gives more frequent contact and stable weekdays, while <a href="/week-on-week-off-custody-schedule/" class="text-accent hover:underline">alternating weeks</a> has fewer exchanges and simpler weekly blocks. Alternating weeks may work better for older children who can handle a full week in each home.',
		},
		{
			question: 'What if parents live far apart?',
			answer: '2-2-5-5 can be difficult when parents live far apart because weekday exchanges, school transportation, and activities may become stressful. Longer-block schedules or a non-50/50 schedule may be more practical.',
			answerHtml: '2-2-5-5 can be difficult when parents live far apart because weekday exchanges, school transportation, and activities may become stressful. Longer-block schedules or a non-50/50 schedule, such as <a href="/60-40-custody-schedule/" class="text-accent hover:underline">60/40</a>, <a href="/70-30-custody-schedule/" class="text-accent hover:underline">70/30</a>, <a href="/80-20-custody-schedule/" class="text-accent hover:underline">80/20</a>, or <a href="/every-other-weekend-custody-schedule/" class="text-accent hover:underline">every other weekend</a>, may be more practical.',
		},
		{
			question: 'Can siblings follow the same schedule?',
			answer: 'Siblings often follow the same schedule to keep routines consistent, but age, school needs, activities, and special circumstances may require adjustments. Parents should focus on what is practical and child-centered.',
		},
		{
			question: 'Is a 2-2-5-5 schedule court-approved?',
			answer: 'Courts may approve many different custody schedules when they meet legal requirements and serve the child’s best interests. This page is educational only and does not guarantee court approval.',
		},
		{
			question: 'Can I use this schedule in a parenting plan?',
			answer: 'You can use a 2-2-5-5 schedule as a starting point for a parenting plan, but the written plan should also address holidays, vacations, exchanges, transportation, changes, decision-making, and dispute resolution.',
			answerHtml: 'You can use a 2-2-5-5 schedule as a starting point for a parenting plan, but the written plan should also address holidays, vacations, exchanges, transportation, changes, decision-making, and dispute resolution. Start with a <a href="/parenting-plan-template/" class="text-accent hover:underline">parenting plan template</a> and review it with a qualified professional.',
		},
	],
	relatedSchedules: [
		'2-2-3-custody-schedule',
		'5-2-2-5-custody-schedule',
		'3-4-4-3-custody-schedule',
		'week-on-week-off-custody-schedule',
		'60-40-custody-schedule',
		'every-other-weekend-custody-schedule',
		'50-50-custody-schedule',
	],
	relatedTools: [
		{ title: 'Parenting Plan Template', slug: 'parenting-plan-template', description: 'Turn your 2-2-5-5 parenting schedule into written parenting plan terms.' },
		{ title: 'Custody Percentage Calculator', slug: 'custody-percentage-calculator', description: 'Estimate parenting time percentages from overnight totals.' },
		{ title: 'Child Support Calculator', slug: 'child-support-calculator', description: 'Review support-planning questions alongside custody schedule decisions.' },
	],
	relatedHeading: 'Related 2-2-5-5 custody schedule tools',
	relatedLinks: [
		{ title: '2-2-3 custody schedule', slug: '2-2-3-custody-schedule', description: 'Compare shorter blocks and more frequent contact.' },
		{ title: '3-4-4-3 custody schedule', slug: '3-4-4-3-custody-schedule', description: 'Review another 50/50 schedule with three- and four-day blocks.' },
		{ title: 'Week-on/week-off custody schedule', slug: 'week-on-week-off-custody-schedule', description: 'See whether full-week blocks are easier for older children.' },
		{ title: '50/50 custody schedules', slug: '50-50-custody-schedule', description: 'Compare common equal parenting time options.' },
		{ title: 'Holiday custody planner', slug: 'holiday-custody-planner', description: 'Plan holidays, school breaks, birthdays, and vacations separately.' },
		{ title: 'Parenting plan template', slug: 'parenting-plan-template', description: 'Write exchange, holiday, vacation, and schedule-change terms.' },
		{ title: 'Child support calculator', slug: 'child-support-calculator', description: 'Review support planning with parenting-time context.' },
		{ title: 'Custody percentage calculator', slug: 'custody-percentage-calculator', description: 'Calculate overnight percentages from the calendar.' },
	],
	article: {
		headline: '2-2-5-5 Custody Schedule',
		authorName: 'CustodyBuilder Editorial Team',
		reviewerName: 'CustodyBuilder Editorial Team',
		datePublished: '2026-06-13',
		dateModified: '2026-06-13',
	},
};

export default schedule;
