import type { ScheduleContent } from './types';

const schedule: ScheduleContent = {
	id: '3443',
	title: '3-4-4-3 Custody Schedule',
	slug: '3-4-4-3-custody-schedule',
	description: 'Create a 3-4-4-3 custody schedule and see how three- and four-day blocks appear on a calendar.',
	metaTitle: '3-4-4-3 Custody Schedule | Calendar Examples & Tips',
	metaDescription: 'See how a 3-4-4-3 custody schedule works on a calendar, when it fits between 2-2-3 and week-on/week-off, and how to preview your dates.',
	canonicalUrl: 'https://custodybuilder.com/3-4-4-3-custody-schedule/',
	lastUpdated: '2026-06-13',
	lede: 'A 3-4-4-3 custody schedule is a two-week shared parenting rotation that alternates three-day and four-day blocks. It can work well for families who want fewer exchanges than a 2-2-3 schedule while still keeping both parents involved each week.',
	trust: {
		reviewerLabel: 'Reviewed for clarity by',
		reviewerName: 'CustodyBuilder Editorial Team',
		reviewerCredential: 'Reviewed for clarity, schedule mechanics, and practical usefulness by the CustodyBuilder Editorial Team.',
		reviewerHref: '/about/',
		authorName: 'CustodyBuilder Editorial Team',
		authorTitle: 'Parenting time calendar and custody schedule planning team',
		authorBio: 'CustodyBuilder creates plain-English custody schedule guides and calendar tools for parents comparing parenting time, printable schedules, and parenting plan language.',
		authorHref: '/about/',
		factCheckedDate: '2026-06-13',
		legalReviewerPlaceholder: 'Not yet reviewed by an attorney. This page is for educational planning only and should not be treated as legal advice.',
		disclaimer: 'This tool is for educational planning only and is not legal advice. Custody laws vary by state. Consult a qualified family law attorney or mediator for legal guidance.',
	},
	hero: {
		definition: 'A 3-4-4-3 custody schedule alternates a 3-day block and a 4-day block, then flips those block lengths the next week so each parent receives seven overnights over two weeks.',
		bestFor: 'families who want a middle-ground 50/50 custody schedule with longer blocks than 2-2-3 but less time apart than week-on/week-off.',
		proChips: ['Usually 50/50', '3-day and 4-day blocks', 'Fewer exchanges than 2-2-3', 'Avoids full week away'],
		conChips: ['Uneven-looking weeks', 'Needs clear start date', 'Weekend planning matters', 'Less frequent contact than 2-2-3'],
		ctas: [
			{ text: 'Generate my 3-4-4-3 calendar', href: '#schedule-generator', variant: 'primary' },
			{ text: 'Download printable schedule', href: '#printable-download', variant: 'secondary' },
			{ text: 'Compare custody schedules', href: '#comparison', variant: 'secondary' },
		],
	},
	atAGlanceTitle: '3-4-4-3 Custody Schedule Summary',
	atAGlance: [
		{ label: 'Parenting time', value: 'Usually 50/50 over two weeks' },
		{ label: 'Rotation length', value: 'Two-week cycle' },
		{ label: 'Week 1 pattern', value: 'Parent A 3 days, Parent B 4 days' },
		{ label: 'Week 2 pattern', value: 'Parent A 4 days, Parent B 3 days' },
		{ label: 'Exchange frequency', value: 'Moderate, fewer than 2-2-3' },
		{ label: 'Best for', value: 'School-age children and families wanting longer blocks' },
		{ label: 'Main advantage', value: 'Easier rhythm with longer parenting blocks' },
		{ label: 'Main challenge', value: 'Some weeks feel uneven until viewed over two weeks' },
		{ label: 'Common use', value: 'Equal parenting plans needing fewer transitions' },
	],
	overview: [
		'The 3-4-4-3 custody schedule gives one parent three days and the other parent four days in week one, then flips the block lengths in week two. The calendar may look uneven inside a single week, but the full two-week cycle usually creates a balanced <a href="/50-50-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">50/50 custody schedule</a> with seven overnights for each parent.',
		'This schedule is a middle ground between frequent-contact schedules and longer-block schedules. Compared with a <a href="/2-2-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-3 custody schedule</a>, it usually has fewer transitions and longer time to settle in each home. Compared with a <a href="/week-on-week-off-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">week-on/week-off schedule</a>, it avoids a full week away from either parent.',
		'Parents often choose 3-4-4-3 when children can handle three- and four-day stretches but still need regular contact with both homes. The schedule works best when the start date, exchange day, and weekend handoff rules are written clearly.',
	],
	printableDownload: {
		title: 'Printable 3-4-4-3 Custody Schedule Downloads',
		description: 'Use the generator above to print or export the two-week 3/4 then 4/3 rotation. The resources below help you review whether the uneven-looking weeks balance correctly before adding holidays or parenting plan terms.',
		options: [
			{ title: 'Printable two-week 3-4-4-3 schedule', description: 'Review the 3-day/4-day week and the 4-day/3-day flip before adding holiday overrides.', status: 'available', href: '#timeline' },
			{ title: 'Monthly custody calendar', description: 'Use the generator above to see how the uneven-looking weeks balance across real calendar dates.', status: 'available', href: '#schedule-generator' },
			{ title: 'Yearly custody calendar', description: 'Export a yearly PDF to check holidays, school breaks, and long weekends against the 3/4 rhythm.', status: 'available', href: '#schedule-generator' },
			{ title: 'Parenting plan worksheet', description: 'Use the sample clause below to define the Week 1 and Week 2 blocks with exact exchange times.', status: 'available', href: '#parenting-plan-language' },
			{ title: 'Holiday planning worksheet', description: 'Use the holiday custody planner to decide how overrides affect the 3-day and 4-day blocks.', status: 'available', href: '/holiday-custody-schedule/' },
		],
		ctas: [
			{ text: 'Generate printable calendar', href: '#schedule-generator', variant: 'primary' },
			{ text: 'Export PDF from the tool', href: '#schedule-generator', variant: 'secondary' },
			{ text: 'Plan holidays separately', href: '/holiday-custody-schedule/', variant: 'secondary' },
		],
		yearOptions: ['Two-week schedule', 'Monthly PDF', 'Yearly PDF', 'Holiday worksheet'],
	},
	timeline: {
		title: 'How the 3-4-4-3 Schedule Works',
		description: 'Week 1 is a 3-day block followed by a 4-day block. Week 2 flips to a 4-day block followed by a 3-day block. The full two-week cycle balances to seven overnights for each parent.',
		weeks: [
			{
				label: 'Week 1',
				blocks: [
					{ parent: 'Parent A', days: 'Mon Tue Wed' },
					{ parent: 'Parent B', days: 'Thu Fri Sat Sun' },
				],
			},
			{
				label: 'Week 2',
				blocks: [
					{ parent: 'Parent A', days: 'Mon Tue Wed Thu' },
					{ parent: 'Parent B', days: 'Fri Sat Sun' },
				],
			},
		],
	},
	parentingPlanLanguage: {
		title: 'Sample 3-4-4-3 Parenting Plan Language',
		description: 'This plain-English sample defines the 3-day/4-day week and the 4-day/3-day flip before it is adapted for a formal parenting plan.',
		clause: 'The parents will follow a repeating two-week 3-4-4-3 parenting schedule. During Week 1, Parent A will have parenting time from Monday at [exchange time] through Thursday at [exchange time], and Parent B will have parenting time from Thursday at [exchange time] through Monday at [exchange time]. During Week 2, Parent A will have parenting time from Monday at [exchange time] through Friday at [exchange time], and Parent B will have parenting time from Friday at [exchange time] through Monday at [exchange time]. The schedule will then repeat. Holiday, school-break, vacation, birthday, Mother’s Day, Father’s Day, and other special-day provisions will override the regular 3-4-4-3 schedule when they apply.',
		disclaimer: 'This sample is educational only. Ask a qualified family law professional to review any 3-4-4-3 parenting plan language before filing or signing.',
	},
	deepDiveSections: [
		{
			id: '3443-vs-223',
			kicker: 'Schedule comparison',
			title: '3-4-4-3 vs 2-2-3: What’s the Difference?',
			paragraphs: [
				'The biggest difference is transition frequency. A 2-2-3 schedule gives children more frequent contact and shorter gaps, while 3-4-4-3 gives each home longer blocks before the next exchange.',
				'For younger children, <a href="/2-2-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-3</a> may feel better because neither parent is away for long. For school-age children who can manage three- and four-day blocks, 3-4-4-3 can provide more routine stability while still avoiding a full week away.',
			],
			items: [
				{ title: 'Contact rhythm', description: '2-2-3 gives more frequent parent contact; 3-4-4-3 gives longer blocks with fewer handoffs.' },
				{ title: 'Transition load', description: '3-4-4-3 usually means fewer transitions and less packing than 2-2-3.' },
				{ title: 'Age fit', description: '2-2-3 may fit younger children; 3-4-4-3 often fits school-age children who handle longer stretches.' },
				{ title: 'Routine stability', description: '3-4-4-3 can make homework, activities, and bedtime routines easier to settle into for several days at a time.' },
			],
		},
		{
			id: '3443-vs-week-on-week-off',
			kicker: 'Schedule comparison',
			title: '3-4-4-3 vs Week-On/Week-Off',
			paragraphs: [
				'Week-on/week-off has fewer exchanges and is easy to remember, but it requires a child to spend a full week away from each parent. The 3-4-4-3 schedule keeps the blocks shorter while still reducing exchanges compared with 2-2-3.',
				'Some families use 3-4-4-3 as a transition schedule before trying <a href="/week-on-week-off-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">week-on/week-off custody</a>. It can help older children build tolerance for longer blocks without immediately moving to a full week in each home.',
			],
			items: [
				{ title: 'Exchange frequency', description: 'Week-on/week-off has fewer exchanges; 3-4-4-3 keeps more frequent contact.' },
				{ title: 'Time away', description: '3-4-4-3 avoids a full week away from either parent.' },
				{ title: 'Transition path', description: '3-4-4-3 can be a middle step before alternating weeks for older children.' },
				{ title: 'Best fit', description: 'Week-on/week-off may be easier for teens; 3-4-4-3 may be better when weekly separation still feels too long.' },
			],
		},
		{
			id: 'holidays-breaks-vacations',
			kicker: 'Special dates',
			title: 'Holidays, School Breaks, and Vacations',
			paragraphs: [
				'Holiday rules in a 3-4-4-3 plan should explain what happens when an override interrupts either the three-day block or the four-day block. A long weekend can shift the balance of the visible week, even though the regular cycle balances over two weeks.',
				'Parents should decide whether the regular schedule resumes where it left off or restarts after the holiday. Thanksgiving, winter break, spring break, summer vacation, child birthdays, Mother’s Day, and Father’s Day should have clear start and end times. Use the <a href="/holiday-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">holiday custody planner</a> before adding terms to a <a href="/parenting-plan-template/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">parenting plan template</a>.',
			],
			items: [
				{ title: 'Thanksgiving and long weekends', description: 'Long weekends can swallow most of a three-day block, so the plan should say whether makeup time applies.' },
				{ title: 'Winter and spring breaks', description: 'Breaks can be split by week, by midpoint, or alternated by year depending on travel and school calendars.' },
				{ title: 'Summer vacation', description: 'Summer blocks should state whether the 3-4-4-3 rotation pauses or continues underneath the vacation.' },
				{ title: 'Birthdays and parent days', description: 'Child birthdays, Mother’s Day, and Father’s Day need exact times so they do not confuse the 3/4 handoff rhythm.' },
			],
		},
		{
			id: 'exchange-times-locations',
			kicker: 'Exchanges',
			title: 'Exchange Times and Locations',
			paragraphs: [
				'The 3-4-4-3 schedule is easiest when the exchange time is consistent. Wednesday or Thursday transitions can work well around school pickup because the child moves homes between the three-day and four-day portions of the cycle.',
				'Friday or Sunday exchanges can affect weekend activities, sports, work schedules, and travel. Parents should write whether extracurricular transportation follows the parent on duty or the parent who enrolled the child.',
			],
			items: [
				{ title: 'School exchange', description: 'Works well for midweek Wednesday or Thursday transitions because the school day becomes the handoff point.' },
				{ title: 'Daycare exchange', description: 'Useful for younger children when the 3-day or 4-day block starts after a care day.' },
				{ title: 'Public-location exchange', description: 'Can reduce conflict, but travel time should not make the 3-day block feel rushed.' },
				{ title: 'Home exchange', description: 'Convenient when parents cooperate and weekend gear is ready before the handoff.' },
				{ title: 'Evening exchange', description: 'Can fit work schedules, but late exchanges can disrupt the first bedtime in a longer block.' },
			],
		},
		{
			id: 'communication-tips',
			kicker: 'Co-parenting',
			title: 'Communication Tips for a 3-4-4-3 Schedule',
			paragraphs: [
				'Because each parent may have either a 3-day or a 4-day block, parents should pass schoolwork, medications, uniforms, sports gear, and activity notes before the longer block starts. The longer block is where missed details tend to create the most disruption.',
				'Use a shared calendar to mark the flip week clearly. Confirm whether extracurricular transportation follows the parent on duty or the parent who registered the child. Keep notes short, factual, and tied to the upcoming block.',
			],
			items: [
				{ title: 'Shared calendar', description: 'Label Week 1 and Week 2 so parents can see when the 3-day and 4-day blocks switch.' },
				{ title: 'Schoolwork and medication', description: 'Transfer assignments, devices, medication, and supplies before the four-day block begins.' },
				{ title: 'Uniforms and sports gear', description: 'Pack activity gear before Friday or weekend transitions so practices and games are not missed.' },
				{ title: 'Schedule changes', description: 'State whether a changed block creates makeup time or simply resumes at the next scheduled exchange.' },
			],
		},
		{
			id: 'alternatives',
			kicker: 'Alternatives',
			title: 'Alternatives to 3-4-4-3',
			paragraphs: [
				'If 3-4-4-3 feels too long, compare <a href="/2-2-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-3</a> for more frequent contact. If the family wants fixed weekdays or different five-day blocks, compare <a href="/2-2-5-5-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-5-5</a> or <a href="/5-2-2-5-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">5-2-2-5</a>.',
				'If the midweek 3/4 handoff is not realistic, compare <a href="/60-40-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">60/40</a>, <a href="/70-30-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">70/30</a>, <a href="/80-20-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">80/20</a>, or <a href="/every-other-weekend-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">every other weekend</a> schedules with fewer school-week transitions.',
			],
		},
	],
	pros: [
		'Longer blocks than 2-2-3 without moving to a full week away.',
		'Usually fewer exchanges than frequent-contact schedules.',
		'The 3/4 and 4/3 rhythm can be easier to remember once the two-week cycle is clear.',
		'Each parent gets a meaningful block for school routines, activities, and weekend time.',
		'Works as a middle ground between 2-2-3 and week-on/week-off.',
	],
	cons: [
		'One week may look uneven until parents view the full two-week cycle.',
		'The start date and exchange time must be clear or the 3/4 rhythm can be misread.',
		'Children have fewer touchpoints than they would in a 2-2-3 schedule.',
		'Longer drives can make the midweek exchange harder to manage.',
		'Weekend activities need clear transportation rules because some blocks include Friday through Sunday.',
	],
	example: {
		title: '3-4-4-3 Schedule Example',
		description: 'In week one, Parent A has Monday through Wednesday and Parent B has Thursday through Sunday. In week two, Parent A has Monday through Thursday and Parent B has Friday through Sunday. The schedule looks uneven by week but balances over the full two-week cycle.',
		weeks: [
			{
				label: 'Week 1',
				blocks: [
					{ parent: 'Parent A', days: 'Mon Tue Wed' },
					{ parent: 'Parent B', days: 'Thu Fri Sat Sun' },
				],
			},
			{
				label: 'Week 2',
				blocks: [
					{ parent: 'Parent A', days: 'Mon Tue Wed Thu' },
					{ parent: 'Parent B', days: 'Fri Sat Sun' },
				],
			},
		],
	},
	comparison: {
		title: 'Compare 3-4-4-3 with other custody schedules',
		description: 'Use this table to compare 3-4-4-3 with nearby equal-time and non-equal-time options before choosing a custody calendar pattern.',
		columnLabels: {
			schedule: 'Schedule',
			bestFor: 'Best age group',
			exchangeFrequency: 'Exchanges',
			weekendPattern: 'Stability',
			notes: 'Pros',
		},
		rows: [
			{ schedule: '3-4-4-3', href: '/3-4-4-3-custody-schedule/', bestFor: 'School-age children who can handle 3- and 4-day blocks.', parentTimeSplit: 'Usually 50/50', exchangeFrequency: 'Moderate, fewer than 2-2-3', weekendPattern: 'Two-week 3/4 then 4/3 rhythm', notes: 'Middle ground between frequent contact and full-week blocks.', cons: 'Some weeks look uneven until the full cycle is viewed.', guideLabel: 'Current guide', badge: 'Current page' },
			{ schedule: '2-2-3', href: '/2-2-3-custody-schedule/', bestFor: 'Younger children needing frequent contact.', parentTimeSplit: 'Usually 50/50', exchangeFrequency: '3-4 exchanges per week', weekendPattern: 'Alternating weekends', notes: 'Shorter gaps between parents.', cons: 'More handoffs and more packing.', guideLabel: '2-2-3 guide' },
			{ schedule: '2-2-5-5', href: '/2-2-5-5-custody-schedule/', bestFor: 'Families wanting stable weekday assignments.', parentTimeSplit: 'Usually 50/50', exchangeFrequency: '2-3 exchanges per week', weekendPattern: 'Longer five-day blocks', notes: 'Can create consistent weekday responsibilities.', cons: 'Five-day stretches may feel long.', guideLabel: '2-2-5-5 guide' },
			{ schedule: '5-2-2-5', href: '/5-2-2-5-custody-schedule/', bestFor: 'Families wanting full school-week blocks.', parentTimeSplit: 'Usually 50/50', exchangeFrequency: 'Usually fewer than 2-2-3', weekendPattern: 'School-week/weekend flip', notes: 'One home carries the full school week, then flips.', cons: 'Weekend-only short block may feel limited.', guideLabel: '5-2-2-5 guide' },
			{ schedule: 'Week-on/week-off', href: '/week-on-week-off-custody-schedule/', bestFor: 'Older children and teens.', parentTimeSplit: 'Usually 50/50', exchangeFrequency: '1 exchange per week', weekendPattern: 'High stability', notes: 'Simplest equal-time calendar.', cons: 'A full week away may be too long.', guideLabel: 'Week-on/week-off guide' },
			{ schedule: 'Every other weekend', href: '/every-other-weekend-custody-schedule/', bestFor: 'Families where one home anchors school-week routines.', parentTimeSplit: 'Often 80/20 to 85/15', exchangeFrequency: 'Usually every other weekend', weekendPattern: 'Primary-home stability', notes: 'Low transition load.', cons: 'Much less weekday time for one parent.', guideLabel: 'Every other weekend guide' },
		],
		cta: {
			title: 'Compare other custody schedules',
			links: [
				{ title: '2-2-3 custody schedule', slug: '2-2-3-custody-schedule', description: 'Compare shorter blocks and more frequent contact.' },
				{ title: '2-2-5-5 custody schedule', slug: '2-2-5-5-custody-schedule', description: 'Review fixed weekday assignments and longer five-day blocks.' },
				{ title: '5-2-2-5 custody schedule', slug: '5-2-2-5-custody-schedule', description: 'Compare the school-week/weekend flip pattern.' },
				{ title: 'Week-on/week-off custody schedule', slug: 'week-on-week-off-custody-schedule', description: 'See whether a full-week rotation fits older children.' },
				{ title: 'Every other weekend schedule', slug: 'every-other-weekend-custody-schedule', description: 'Compare a lower-transition schedule when 50/50 is not realistic.' },
			],
		},
	},
	faq: [
		{ question: 'What is a 3-4-4-3 custody schedule?', answer: 'A 3-4-4-3 custody schedule is a repeating two-week parenting plan with a 3-day block, then a 4-day block, then a 4-day block, then a 3-day block. The visible weeks look uneven, but the full cycle usually gives each parent seven overnights.' },
		{ question: 'How does a 3-4-4-3 schedule work?', answer: 'Week 1 commonly gives Parent A Monday through Wednesday and Parent B Thursday through Sunday. Week 2 flips the longer block so Parent A has Monday through Thursday and Parent B has Friday through Sunday.' },
		{ question: 'Is 3-4-4-3 always 50/50?', answer: 'The standard two-week 3-4-4-3 pattern is usually 50/50 because each parent receives seven overnights. The annual total can change when holidays, vacations, or school-break rules override the regular cycle.' },
		{ question: 'Is 3-4-4-3 better than 2-2-3?', answer: '3-4-4-3 may be better when a child can handle longer blocks and the family wants fewer transitions. 2-2-3 may work better when a younger child needs more frequent contact with each parent.', answerHtml: '3-4-4-3 may be better when a child can handle longer blocks and the family wants fewer transitions. A <a href="/2-2-3-custody-schedule/" class="text-accent hover:underline">2-2-3 custody schedule</a> may work better when a younger child needs more frequent contact with each parent.' },
		{ question: 'Is 3-4-4-3 better than 2-2-5-5?', answer: '3-4-4-3 may be better when parents want no block longer than four days. 2-2-5-5 may be better when fixed weekdays or longer five-day stretches are more important.', answerHtml: '3-4-4-3 may be better when parents want no block longer than four days. A <a href="/2-2-5-5-custody-schedule/" class="text-accent hover:underline">2-2-5-5 custody schedule</a> may be better when fixed weekdays or longer five-day stretches are more important.' },
		{ question: 'How many exchanges does 3-4-4-3 require?', answer: 'The exact number depends on the written exchange times, but it generally requires fewer exchanges than 2-2-3 and more exchanges than week-on/week-off. The main handoffs happen between the 3-day and 4-day blocks.' },
		{ question: 'How are holidays handled?', answer: 'Holiday rules should say whether a holiday replaces a 3-day block, a 4-day block, or only the specific holiday hours. The plan should also say whether the regular cycle resumes where it left off or restarts after the holiday.', answerHtml: 'Holiday rules should say whether a holiday replaces a 3-day block, a 4-day block, or only the specific holiday hours. The <a href="/holiday-custody-schedule/" class="text-accent hover:underline">holiday custody planner</a> can help map those exceptions.' },
		{ question: 'What if parents live far apart?', answer: '3-4-4-3 can be difficult when parents live far apart because midweek exchanges still happen. If driving time makes school or activities hard, a longer-block schedule or unequal-time schedule may be more practical.', answerHtml: '3-4-4-3 can be difficult when parents live far apart because midweek exchanges still happen. If driving time makes school or activities hard, compare <a href="/60-40-custody-schedule/" class="text-accent hover:underline">60/40</a>, <a href="/70-30-custody-schedule/" class="text-accent hover:underline">70/30</a>, <a href="/80-20-custody-schedule/" class="text-accent hover:underline">80/20</a>, or <a href="/every-other-weekend-custody-schedule/" class="text-accent hover:underline">every other weekend</a> schedules.' },
	],
	relatedSchedules: [
		'2-2-3-custody-schedule',
		'2-2-5-5-custody-schedule',
		'5-2-2-5-custody-schedule',
		'week-on-week-off-custody-schedule',
		'60-40-custody-schedule',
		'every-other-weekend-custody-schedule',
		'50-50-custody-schedule',
	],
	relatedTools: [
		{ title: 'Parenting Plan Template', slug: 'parenting-plan-template', description: 'Turn your 3-4-4-3 parenting schedule into written parenting plan terms.' },
		{ title: 'Custody Percentage Calculator', slug: 'custody-percentage-calculator', description: 'Estimate parenting time percentages from overnight totals.' },
		{ title: 'Child Support Calculator', slug: 'texas-child-support-calculator', description: 'Review support-planning questions alongside custody schedule decisions.' },
	],
	relatedHeading: 'Related 3-4-4-3 custody schedule tools',
	relatedLinks: [
		{ title: '2-2-3 custody schedule', slug: '2-2-3-custody-schedule', description: 'Compare shorter blocks and more frequent contact.' },
		{ title: '2-2-5-5 custody schedule', slug: '2-2-5-5-custody-schedule', description: 'Review fixed weekday assignments and longer five-day blocks.' },
		{ title: '5-2-2-5 custody schedule', slug: '5-2-2-5-custody-schedule', description: 'Compare the school-week/weekend flip pattern.' },
		{ title: 'Week-on/week-off custody schedule', slug: 'week-on-week-off-custody-schedule', description: 'See whether a full-week rotation fits older children.' },
		{ title: '50/50 custody schedules', slug: '50-50-custody-schedule', description: 'Compare common equal parenting time options.' },
		{ title: 'Holiday custody planner', slug: 'holiday-custody-schedule', description: 'Plan holidays, school breaks, birthdays, and vacations separately.' },
		{ title: 'Parenting plan template', slug: 'parenting-plan-template', description: 'Write exchange, holiday, vacation, and schedule-change terms.' },
		{ title: 'Custody percentage calculator', slug: 'custody-percentage-calculator', description: 'Calculate overnight percentages from the calendar.' },
	],
	article: {
		headline: '3-4-4-3 Custody Schedule',
		authorName: 'CustodyBuilder Editorial Team',
		reviewerName: 'CustodyBuilder Editorial Team',
		datePublished: '2026-06-13',
		dateModified: '2026-06-13',
	},
};

export default schedule;
