import type { ScheduleContent } from './types';

const schedule: ScheduleContent = {
	id: '50-50',
	title: '50/50 Custody Schedule: Examples, Calendar & Free Generator',
	slug: '50-50-custody-schedule',
	description: 'Compare 50/50 custody schedules, generate a printable custody calendar, and calculate overnight parenting time.',
	metaTitle: '50/50 Custody Schedule: Examples, Calendar & Free Generator',
	metaDescription: 'Compare 50/50 custody schedules like 2-2-3, 2-2-5-5, 3-4-4-3 and week-on/week-off. Generate a printable custody calendar and calculate parenting time.',
	ogTitle: '50/50 Custody Schedule Generator',
	ogDescription: 'Build and compare 50/50 parenting schedules with a free printable calendar.',
	canonicalUrl: 'https://custodybuilder.com/50-50-custody-schedule/',
	lastUpdated: '2026-06-17',
	lede: 'Compare the most common 50/50 parenting schedules — 2-2-3, 2-2-5-5, 3-4-4-3, 5-2-2-5, and week-on/week-off — then generate a printable custody calendar.',
	trust: {
		reviewerLabel: 'Editorial review',
		reviewerName: 'CustodyBuilder Editorial Team',
		reviewerCredential: 'Reviewed for clarity, schedule comparison logic, and practical usefulness by the CustodyBuilder Editorial Team.',
		reviewerHref: '/about/',
		authorName: 'CustodyBuilder Editorial Team',
		authorTitle: 'Parenting time calendar and custody schedule planning team',
		authorBio: 'CustodyBuilder creates plain-English schedule guides and calendar tools for parents comparing overnights, printable calendars, and parenting plan options.',
		authorHref: '/about/',
		factCheckedDate: '2026-06-17',
		legalReviewerPlaceholder: 'Not attorney-reviewed. This page is educational information, not legal advice or a court order.',
		disclaimer: 'Use this guide for planning conversations. Custody laws, child support rules, and court practices vary by state.',
	},
	hero: {
		definition: 'A 50/50 custody schedule gives each parent roughly equal parenting time. The most common options are 2-2-3, 2-2-5-5, 3-4-4-3, 5-2-2-5, and week-on/week-off.',
		bestFor: 'parents comparing equal parenting time schedules before generating a printable 50/50 custody calendar.',
		proChips: ['Free custody calendar generator', 'Printable schedule preview', 'Calculate overnight split', 'No account required'],
		conChips: ['Distance matters', 'Exchange routine matters', 'Holidays can shift totals', 'Not legal advice'],
		ctas: [
			{ text: 'Generate My 50/50 Calendar', href: '#schedule-generator', variant: 'primary' },
			{ text: 'Compare 50/50 Schedules', href: '#comparison', variant: 'secondary' },
		],
	},
	atAGlanceTitle: '50/50 custody schedule summary',
	atAGlance: [
		{ label: 'Primary intent', value: 'Choose, generate, print, and compare a 50/50 custody schedule' },
		{ label: 'Typical annual split', value: 'About 182-183 overnights per parent per year' },
		{ label: 'Common schedules', value: '2-2-3, 2-2-5-5, 3-4-4-3, 5-2-2-5, week-on/week-off' },
		{ label: 'Best young-child option', value: '2-2-3 or 2-2-5-5 when exchanges are calm and nearby' },
		{ label: 'Best school-age option', value: '2-2-5-5 when weekday routines need to repeat clearly' },
		{ label: 'Lowest-exchange option', value: 'Week-on/week-off, usually best for older children and teenagers' },
		{ label: 'Printable output', value: 'Monthly calendar, yearly PDF, color-coded parent days, and overnight estimate' },
		{ label: 'Next planning step', value: 'Add holidays, school breaks, transportation, and exchange rules to a parenting plan' },
	],
	overviewTitle: 'What is a 50/50 custody schedule?',
	overview: [
		'A 50/50 custody schedule, also called a <strong>50/50 parenting schedule</strong>, <strong>shared custody schedule</strong>, <strong>joint custody schedule</strong>, or <strong>equal parenting time schedule</strong>, is a calendar pattern that keeps parenting time roughly balanced between two homes.',
		'The best 50/50 custody schedule is not always the neatest-looking calendar. It is the rotation that a child can follow consistently around school, sleep, activities, distance between homes, parent work schedules, and exchange stress.',
		'Use the generator above to test real start dates, rename Parent A and Parent B, calculate the overnight split, print a monthly preview, or save a PDF. Then compare the detailed guides for <a href="/2-2-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-3</a>, <a href="/2-2-5-5-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-5-5</a>, <a href="/5-2-2-5-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">5-2-2-5</a>, <a href="/3-4-4-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">3-4-4-3</a>, and <a href="/week-on-week-off-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">week-on/week-off</a>.',
	],
	printableDownload: {
		title: 'Generate a printable 50/50 custody calendar',
		description: 'Choose a schedule pattern, pick a start date, rename Parent A and Parent B, then print your calendar or save it for later.',
		options: [
			{ title: 'Monthly calendar', description: 'Preview a color-coded month with Parent A and Parent B days before printing.', status: 'available', href: '#schedule-generator' },
			{ title: 'Yearly PDF', description: 'Save a longer planning view after choosing the 50/50 rotation and start date.', status: 'available', href: '#schedule-generator' },
			{ title: 'Saved schedules', description: 'Save this schedule to an account and return to it later.', status: 'coming-soon' },
		],
		ctas: [
			{ text: 'Generate 50/50 Calendar', href: '#schedule-generator', variant: 'primary' },
			{ text: 'Print Calendar', href: '#schedule-generator', variant: 'secondary' },
			{ text: 'Save This Schedule', href: '#schedule-generator', variant: 'secondary', disabled: true },
		],
		yearOptions: ['Printable 50/50 custody calendar', '50/50 custody calendar PDF', 'Monthly calendar', 'Yearly calendar', 'Color-coded parent days', 'Holiday notes'],
	},
	deepDiveSections: [
		{
			id: 'overnight-calculator',
			kicker: 'Overnight calculator',
			title: '50/50 custody overnight calculator',
			paragraphs: [
				'True 50/50 parenting time usually means each parent has about 182-183 overnights per year. A repeating two-week schedule may look exactly equal, but holidays, school breaks, vacations, and make-up time can shift the annual total.',
				'After you generate a calendar, use the calculator tools to check the full-year parenting time percentage before relying on the schedule for planning conversations.',
			],
			items: [
				{ title: 'Calculate custody percentage', description: 'Use the <a href="/custody-percentage-calculator/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">custody percentage calculator</a> to convert overnights into annual parenting time.' },
				{ title: 'Compare parenting time', description: 'Use the <a href="/parenting-time-calculator/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">parenting time calculator</a> to compare 50/50 schedules with 60/40, 70/30, or custom plans.' },
			],
		},
		{
			id: 'when-50-50-works',
			kicker: 'Best fit',
			title: 'When 50/50 custody usually works best',
			paragraphs: [
				'50/50 custody usually works best when the child can move between two stable homes without school disruption, long commutes, or repeated conflict around exchanges.',
			],
			items: [
				{ title: 'Parents live reasonably close', description: 'Both homes can support school, activities, friends, medical care, and ordinary routines without long drives.' },
				{ title: 'School commute is manageable', description: 'The child can get to school on time from either home without rushed mornings or missed activities.' },
				{ title: 'Both homes are stable', description: 'Each home can handle bedtime, meals, homework, supplies, medication, and supervision during its scheduled time.' },
				{ title: 'Exchange routine is consistent', description: 'Parents can follow the same pickup time, location, transportation rule, and backup plan.' },
				{ title: 'The child can handle transitions', description: 'The schedule gives the child enough emotional reset time after each move between homes.' },
			],
		},
		{
			id: 'when-50-50-not-work',
			kicker: 'Watch-outs',
			title: 'When 50/50 custody may not work well',
			paragraphs: [
				'Equal parenting time should not be forced when the calendar creates repeated school problems, unsafe exchanges, unstable supervision, or transition stress for the child.',
			],
			items: [
				{ title: 'Long distance between homes', description: 'A schedule can be equal on paper but too hard if one home cannot support school-week mornings and activities.' },
				{ title: 'High-conflict exchanges', description: 'Frequent handoffs can expose the child to more tension unless exchanges happen through school or another neutral structure.' },
				{ title: 'Unsafe or unstable home environment', description: 'Safety, supervision, housing stability, substance use, domestic violence, or medical concerns require local professional guidance.' },
				{ title: 'Infant or toddler separation needs', description: 'Very young children may need shorter separations, more frequent contact, or a phased schedule rather than long blocks.' },
				{ title: 'Unpredictable work schedules', description: 'Rotating shifts, travel, call-ins, or last-minute overtime can make a standard equal-time rotation unreliable.' },
			],
		},
		{
			id: 'printable-calendar',
			kicker: 'Printable calendar',
			title: 'Printable 50/50 custody calendar',
			paragraphs: [
				'A printable 50/50 custody calendar helps parents see the actual month, not just the schedule name. CustodyBuilder can generate a monthly calendar, yearly calendar, and 50/50 custody calendar PDF with color-coded parent days.',
				'Use the printable view for planning conversations, mediation prep, school-year organization, and holiday notes. Add holiday rules separately because Thanksgiving, winter break, spring break, summer vacation, birthdays, and parent holidays can override the regular 50/50 rotation.',
			],
			items: [
				{ title: 'Monthly calendar', description: 'Good for seeing the next school month, activities, exchanges, and short-term planning.' },
				{ title: 'Yearly calendar PDF', description: 'Better for checking annual overnights, vacations, holidays, and the full parenting time pattern.' },
				{ title: 'Color-coded parent days', description: 'Parent A and Parent B days are easier to scan before printing or discussing the plan.' },
				{ title: 'Holiday notes', description: 'Use a separate <a href="/holiday-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">holiday custody schedule</a> when special days override the regular calendar.' },
			],
		},
	],
	pros: [
		'Both parents stay actively involved in ordinary weekday and weekend routines.',
		'Children can maintain strong relationships with both homes when logistics are stable.',
		'Parenting responsibilities are more balanced across school, bedtime, activities, and weekends.',
		'It can reduce the feeling that one parent is only the visitor.',
	],
	cons: [
		'Requires communication, punctual exchanges, and clear shared expectations.',
		'Frequent exchanges can be stressful for children or parents.',
		'Harder when parents live far apart or school transportation is uneven.',
		'Not ideal for every child age, safety concern, work schedule, or conflict level.',
	],
	example: {
		title: '50/50 custody schedule examples',
		description: 'These mini examples show how common 50/50 calendars repeat. Open the full schedule guide for more detailed calendars, variations, and planning notes.',
		weeks: [
			{
				label: '2-2-3 weekly example',
				blocks: [
					{ parent: 'Parent A', days: 'Mon-Tue' },
					{ parent: 'Parent B', days: 'Wed-Thu' },
					{ parent: 'Parent A', days: 'Fri-Sun' },
				],
			},
			{
				label: 'Week-on/week-off example',
				blocks: [
					{ parent: 'Parent A', days: 'Week 1' },
					{ parent: 'Parent B', days: 'Week 2' },
					{ parent: 'Repeats', days: 'One exchange per week' },
				],
			},
		],
	},
	comparison: {
		title: 'Compare common 50/50 custody schedules',
		description: 'Use this comparison to choose the right 50/50 visitation schedule or joint custody schedule before generating a calendar. Each option can produce roughly equal parenting time, but the exchange load and child fit are different.',
		columnLabels: {
			schedule: '50/50 custody schedule',
			bestFor: 'Best for',
			exchangeFrequency: 'Exchange frequency',
			weekendPattern: 'Main advantage',
			notes: 'Main drawback',
		},
		rows: [
			{ schedule: '2-2-3 custody schedule', href: '/2-2-3-custody-schedule/', bestFor: 'Toddlers, preschoolers, and children who need shorter gaps between homes.', parentTimeSplit: 'Usually 50/50 over two weeks', exchangeFrequency: 'High: several exchanges each week', weekendPattern: 'Frequent contact and alternating long weekends', notes: 'More packing, driving, and handoff opportunities.', cons: 'Frequent exchanges can be too much if parents live far apart or conflict is high.', guideLabel: 'Open 2-2-3 guide' },
			{ schedule: '2-2-5-5 custody schedule', href: '/2-2-5-5-custody-schedule/', bestFor: 'School-age children who benefit from fixed weekday routines.', parentTimeSplit: 'Usually 50/50 over two weeks', exchangeFrequency: 'Moderate', weekendPattern: 'Same weekdays repeat for each parent', notes: 'Five-day blocks may feel long for younger children.', cons: 'Needs both homes ready for school-night responsibility.', guideLabel: 'Open 2-2-5-5 guide' },
			{ schedule: '5-2-2-5 custody schedule', href: '/5-2-2-5-custody-schedule/', bestFor: 'Middle-school children or families that want longer school-week blocks.', parentTimeSplit: 'Usually 50/50 over two weeks', exchangeFrequency: 'Moderate to low', weekendPattern: 'Longer blocks reduce constant transitions', notes: 'Short two-day blocks can feel uneven if not planned well.', cons: 'Requires clear supplies and activity systems in both homes.', guideLabel: 'Open 5-2-2-5 guide' },
			{ schedule: '3-4-4-3 custody schedule', href: '/3-4-4-3-custody-schedule/', bestFor: 'Families wanting a middle ground between frequent contact and full weeks.', parentTimeSplit: 'Usually 50/50 over two weeks', exchangeFrequency: 'Moderate', weekendPattern: 'No full week away from either parent', notes: 'The pattern can look uneven unless parents track the two-week cycle.', cons: 'Start-date confusion is common without a clear calendar.', guideLabel: 'Open 3-4-4-3 guide' },
			{ schedule: 'Week-on/week-off custody schedule', href: '/week-on-week-off-custody-schedule/', bestFor: 'Teenagers and older children who can handle full weeks in each home.', parentTimeSplit: 'Usually 50/50 over two weeks', exchangeFrequency: 'Low: usually one exchange per week', weekendPattern: 'Simplest calendar and fewest exchanges', notes: 'A full week away can be too long for younger children.', cons: 'Requires both homes to support a full school week.', guideLabel: 'Open week-on/week-off guide' },
		],
		cta: {
			title: 'Try this schedule in the free generator',
			links: [
				{ title: 'Generate a 50/50 custody calendar', slug: '50-50-custody-schedule', description: 'Use the generator above to test the schedule with real dates.' },
				{ title: 'Compare another schedule', slug: '60-40-custody-schedule', description: 'Compare 60/40 if equal time is too hard for school, distance, or work logistics.' },
				{ title: 'Use a custody calendar template', slug: 'custody-calendar-template', description: 'Turn the chosen schedule into a printable planning calendar.' },
				{ title: 'Draft parenting plan terms', slug: 'parenting-plan-template', description: 'Add exchange time, transportation, holiday, and review language.' },
			],
		},
	},
	decisionGuide: {
		quickAnswer: {
			title: 'Quick answer',
			description: 'A 50/50 custody schedule gives each parent roughly equal parenting time. The most common options are 2-2-3, 2-2-5-5, 3-4-4-3, 5-2-2-5, and week-on/week-off. For younger children, 2-2-3 often works better because it avoids long gaps. For school-age children, 2-2-5-5 is often easier. For teenagers, week-on/week-off can work if both homes are stable.',
			items: [
				{ label: 'Generate calendar', title: 'Build a printable 50/50 custody calendar', href: '#schedule-generator' },
				{ label: 'Compare schedules', title: 'Review the five common 50/50 options', href: '#comparison' },
				{ label: 'Calculate time', title: 'Check annual overnight totals', href: '#overnight-calculator' },
			],
		},
		byAge: {
			title: 'Best 50/50 schedule by age',
			description: 'Age does not decide custody by itself, but it changes how children experience separations, exchanges, school routines, and time away from each home.',
			rows: [
				{ age: 'Toddlers', recommended: '2-2-3 or 2-2-5-5', href: '/2-2-3-custody-schedule/', guideHref: '/best-custody-schedule-for-toddler/', reason: 'Shorter gaps can help, but only when exchanges are calm and homes are close.' },
				{ age: 'Preschool', recommended: '2-2-3 or 3-4-4-3', href: '/3-4-4-3-custody-schedule/', guideHref: '/best-custody-schedule-for-5-year-old/', reason: 'Preschoolers may still need frequent contact while slowly tolerating longer blocks.' },
				{ age: 'Elementary school', recommended: '2-2-5-5', href: '/2-2-5-5-custody-schedule/', guideHref: '/best-custody-schedule-for-7-year-old/', reason: 'Fixed weekdays help with homework, backpacks, reading logs, lunches, and activities.' },
				{ age: 'Middle school', recommended: '5-2-2-5 or week-on/week-off', href: '/5-2-2-5-custody-schedule/', guideHref: '/best-custody-schedule-for-teenager/', reason: 'Older children often need fewer handoffs around activities, devices, and school responsibilities.' },
				{ age: 'Teenagers', recommended: 'Week-on/week-off', href: '/week-on-week-off-custody-schedule/', guideHref: '/best-custody-schedule-for-teenager/', reason: 'Teens often do better with a simpler calendar if both homes can support a full week.' },
			],
			ageGuideNotes: [
				'Teenagers often need more flexibility around driving, jobs, sports, friendships, and social commitments. See our guide on <a href="/50-50-custody-schedule-for-teenagers/" class="font-semibold text-accent underline decoration-line underline-offset-4 hover:text-primary">50/50 custody schedules for teenagers</a>.',
			],
		},
		logistics: {
			title: 'What to define before using a 50/50 parenting schedule',
			description: [
				'The schedule name is only the start. A workable 50/50 parenting schedule also needs written rules for school supplies, exchanges, holidays, transportation, missed time, and schedule changes.',
				'Use the calendar first, then turn the pattern into practical language with a <a href="/parenting-plan-template/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">parenting plan template</a>.',
			],
			items: [
				'Exact exchange time and location',
				'Who drives or whether exchanges happen at school',
				'How backpacks, medicine, devices, uniforms, and sports gear move',
				'What happens when school is closed or a child is sick',
				'How holidays override the regular 50/50 rotation',
				'How parents request changes or make up missed time',
			],
		},
		insight: {
			title: '50/50 custody and child support',
			description: [
				'50/50 parenting time does not automatically mean no child support. Courts may still consider income, expenses, healthcare, childcare, and state-specific formulas.',
				'The calendar still matters because it helps parents document the actual annual overnight count. Build the full schedule first, including holidays and school breaks, then estimate support with custody time included.',
			],
		},
		childSupport: {
			title: '50/50 custody and child support',
			description: [
				'50/50 parenting time does not automatically mean no child support. Courts may still consider income, expenses, healthcare, childcare, and state-specific formulas.',
				'Use the 50/50 custody calendar as a planning record, not as a legal answer. If support is disputed, compare the parenting time totals with local rules or qualified professional guidance.',
			],
			factors: ['Annual overnights', 'Parent income', 'Healthcare', 'Childcare', 'State formulas', 'Special expenses'],
			ctaText: 'Estimate child support with custody time',
		},
		decisionSummary: {
			title: 'Build the 50/50 calendar before choosing final wording',
			description: [
				'The strongest 50/50 custody schedule is the one that survives the real calendar: school mornings, weekends, exchanges, holidays, activities, and parent work schedules.',
				'Generate the calendar, print it, calculate overnights, then use a parenting plan template to write the exact exchange and holiday rules.',
			],
			primaryCta: { text: 'Generate 50/50 Calendar', href: '#schedule-generator' },
			secondaryCta: { text: 'Print your 50/50 calendar', href: '#printable-download' },
		},
		ctaHub: {
			title: 'Related custody schedules and planning tools',
			items: [
				{ title: 'Custody Schedule Generator', slug: 'custody-schedule-generator', description: 'Start from the main custody schedule generator and compare other parenting schedules.' },
				{ title: 'Custody Percentage Calculator', slug: 'custody-percentage-calculator', description: 'Calculate annual parenting time from overnight totals.' },
				{ title: 'Parenting Time Calculator', slug: 'parenting-time-calculator', description: 'Compare 50/50 with unequal parenting time schedules.' },
				{ title: 'Parenting Plan Template', slug: 'parenting-plan-template', description: 'Write exchange, transportation, holiday, and review terms.' },
				{ title: 'Custody Calendar Template', slug: 'custody-calendar-template', description: 'Use a printable template for school calendars, holidays, and activity planning.' },
			],
		},
	},
	examples: {
		title: 'More 50/50 custody schedule examples',
		description: 'Compare these examples when deciding whether your family needs frequent contact, fixed weekdays, or fewer exchanges.',
		libraryPromo: {
			heading: 'Looking for More 50/50 Custody Examples?',
			description:
				'See how these schedules work for toddlers, school-age children, teenagers, holidays, work schedules, and different parenting situations.',
			buttonText: 'Browse All 50/50 Schedule Examples',
			href: '/50-50-custody-schedule-examples/',
		},
		items: [
			{ title: '2-2-3 weekly example', href: '/2-2-3-custody-schedule/', description: 'Parent A has Monday-Tuesday, Parent B has Wednesday-Thursday, and Parent A has Friday-Sunday. The next week flips.', approxSplit: 'About 50/50 over two weeks', bestUseCase: 'Younger children who need shorter gaps between homes.' },
			{ title: '2-2-5-5 two-week example', href: '/2-2-5-5-custody-schedule/', description: 'One parent keeps the same two weekdays, the other keeps the other two weekdays, and weekends alternate through five-day blocks.', approxSplit: 'About 50/50 over two weeks', bestUseCase: 'School-age children who need predictable weekday routines.' },
			{ title: 'Week-on/week-off example', href: '/week-on-week-off-custody-schedule/', description: 'Parent A has one full week, Parent B has the next full week, and the pattern repeats with one weekly exchange.', approxSplit: 'About 50/50 over two weeks', bestUseCase: 'Teenagers and older children who can handle full weeks.' },
		],
	},
	faq: [
		{ question: 'What is a 50/50 custody schedule?', answer: 'A 50/50 custody schedule is a parenting time calendar that gives each parent roughly equal time with the child. Common examples include 2-2-3, 2-2-5-5, 3-4-4-3, 5-2-2-5, and week-on/week-off.' },
		{ question: 'What is the most common 50/50 custody schedule?', answer: 'The most common 50/50 custody schedules are 2-2-3, 2-2-5-5, and week-on/week-off. 2-2-3 is often used for younger children, 2-2-5-5 often fits school-age routines, and week-on/week-off is often simpler for older children and teenagers.' },
		{ question: 'Is 2-2-3 a 50/50 custody schedule?', answer: 'Yes. A 2-2-3 custody schedule usually balances to 50/50 over a two-week cycle because the parent with the three-day weekend in week one usually has the shorter weekday block in week two.' },
		{ question: 'Is 2-2-5-5 better than 2-2-3?', answer: '2-2-5-5 is often better for school-age children because the same weekdays repeat for each parent. 2-2-3 may be better for younger children who need shorter gaps between homes, as long as frequent exchanges are not stressful.' },
		{ question: 'What is the best 50/50 custody schedule for toddlers?', answer: 'Toddlers often do better with shorter separations, so parents commonly compare 2-2-3 or 2-2-5-5 first. The right answer depends on distance, exchange stress, bedtime consistency, and the child’s developmental needs.' },
		{ question: 'What is the best 50/50 custody schedule for school-age children?', answer: 'For school-age children, 2-2-5-5 is often easier because weekday responsibilities repeat. 5-2-2-5 and 3-4-4-3 can also work when both homes can support homework, transportation, activities, and supplies.' },
		{ question: 'Does 50/50 custody eliminate child support?', answer: 'No. 50/50 parenting time does not automatically eliminate child support. Courts may still consider income, healthcare, childcare, expenses, and state-specific formulas.' },
		{ question: 'How many overnights is 50/50 custody?', answer: '50/50 custody usually means about 182-183 overnights per parent per year. Holidays, vacations, and school breaks can change the exact annual total.' },
		{ question: 'Can I print a 50/50 custody calendar?', answer: 'Yes. Use the 50/50 custody schedule generator on this page to preview a calendar, print it, or download monthly and yearly PDF versions for planning.' },
		{ question: 'Can I use this calendar in court?', answer: 'You can use the calendar as an educational planning aid or discussion document, but it is not legal advice, a court order, or a substitute for attorney guidance. Check local requirements before filing or presenting any schedule.' },
		{ question: 'Can 50/50 custody work for high-conflict parents?', answer: 'It can be difficult, especially if the schedule requires frequent direct exchanges. High-conflict parents may need school-based exchanges, fewer handoffs, detailed written rules, or a different parenting time structure.' },
		{ question: 'What if parents live far apart?', answer: '50/50 custody is harder when homes are far apart because school mornings, activities, transportation, and weekday routines may become stressful. Parents may need longer blocks, a custom schedule, or a different split such as 60/40.' },
	],
	relatedSchedules: [
		'2-2-3-custody-schedule',
		'2-2-5-5-custody-schedule',
		'5-2-2-5-custody-schedule',
		'3-4-4-3-custody-schedule',
		'week-on-week-off-custody-schedule',
		'60-40-custody-schedule',
		'70-30-custody-schedule',
		'80-20-custody-schedule',
		'every-other-weekend-custody-schedule',
	],
	relatedTools: [
		{ title: 'Custody schedule generator', slug: 'custody-schedule-generator', description: 'Generate a printable custody calendar with real dates.' },
		{ title: 'Custody percentage calculator', slug: 'custody-percentage-calculator', description: 'Calculate parenting time from annual overnights.' },
		{ title: 'Parenting time calculator', slug: 'parenting-time-calculator', description: 'Compare custody time percentages across schedules.' },
		{ title: 'Parenting plan template', slug: 'parenting-plan-template', description: 'Write schedule, exchange, holiday, and transportation terms.' },
		{ title: 'Custody calendar template', slug: 'custody-calendar-template', description: 'Organize parenting days in a printable calendar format.' },
	],
	relatedHeading: 'Related custody schedules',
	relatedLinks: [
		{ title: 'Best 50/50 Custody Schedule', slug: 'best-50-50-custody-schedule', description: 'Decision guide: compare patterns and choose the best 50/50 schedule for your family.' },
		{ title: '50/50 Schedule Examples', slug: '50-50-custody-schedule-examples', description: 'Browse real calendar scenarios by age, holidays, and parent work schedules.' },
		{ title: '2-2-3 Custody Schedule', slug: '2-2-3-custody-schedule', description: 'Frequent-contact 50/50 schedule with alternating long weekends.' },
		{ title: '2-2-5-5 Custody Schedule', slug: '2-2-5-5-custody-schedule', description: '50/50 schedule with fixed weekdays and alternating five-day blocks.' },
		{ title: '5-2-2-5 Custody Schedule', slug: '5-2-2-5-custody-schedule', description: 'Equal-time schedule with longer blocks and predictable two-week rhythm.' },
		{ title: '3-4-4-3 Custody Schedule', slug: '3-4-4-3-custody-schedule', description: 'Middle-ground 50/50 schedule with three- and four-day blocks.' },
		{ title: 'Week-On/Week-Off Custody Schedule', slug: 'week-on-week-off-custody-schedule', description: 'Lowest-exchange equal parenting time schedule.' },
		{ title: '60/40 Custody Schedule', slug: '60-40-custody-schedule', description: 'Compare when equal time is too hard for distance or school routines.' },
		{ title: '70/30 Custody Schedule', slug: '70-30-custody-schedule', description: 'Compare a primary-home schedule with regular overnights.' },
		{ title: '80/20 Custody Schedule', slug: '80-20-custody-schedule', description: 'Compare a primary-home schedule with less frequent overnights.' },
		{ title: 'Every Other Weekend Custody Schedule', slug: 'every-other-weekend-custody-schedule', description: 'Compare a common visitation schedule against shared custody options.' },
		{ title: 'Custody Schedule Generator', slug: 'custody-schedule-generator', description: 'Generate and print a custody calendar from real dates.' },
		{ title: 'Custody Percentage Calculator', slug: 'custody-percentage-calculator', description: 'Calculate annual parenting time percentages.' },
		{ title: 'Parenting Time Calculator', slug: 'parenting-time-calculator', description: 'Compare overnights and parenting time across schedules.' },
		{ title: 'Parenting Plan Template', slug: 'parenting-plan-template', description: 'Turn a 50/50 calendar into written plan terms.' },
		{ title: 'Custody Calendar Template', slug: 'custody-calendar-template', description: 'Use a printable calendar format for custody planning.' },
	],
	article: {
		headline: '50/50 Custody Schedule: Examples, Calendar & Free Generator',
		authorName: 'CustodyBuilder Editorial Team',
		reviewerName: '',
		datePublished: '2026-06-13',
		dateModified: '2026-06-17',
	},
};

export default schedule;
