import type { ScheduleContent } from './types';

const schedule: ScheduleContent = {
	id: '5225',
	title: '5-2-2-5 Custody Schedule',
	slug: '5-2-2-5-custody-schedule',
	description: 'Generate a 5-2-2-5 custody calendar and compare the benefits and tradeoffs of this 50/50 schedule.',
	metaTitle: '5-2-2-5 Custody Schedule | Examples & Parenting Time',
	metaDescription: 'Learn how a 5-2-2-5 custody schedule works, compare examples, and calculate parenting time percentages.',
	canonicalUrl: 'https://custodybuilder.com/5-2-2-5-custody-schedule/',
	lastUpdated: '2026-06-13',
	lede: 'A 5-2-2-5 custody schedule is a two-week parenting rotation where the child spends 5 days with one parent, 2 days with the other parent, 2 days back with the first parent, and then 5 days with the other parent. It gives families longer parenting blocks and usually fewer exchanges than a 2-2-3 custody schedule.',
	trust: {
		reviewerLabel: 'Reviewed for clarity by',
		reviewerName: 'CustodyBuilder Editorial Team',
		reviewerCredential: 'Reviewed for clarity, schedule mechanics, and practical usefulness by the CustodyBuilder Editorial Team.',
		reviewerHref: '/about/',
		authorName: 'CustodyBuilder Editorial Team',
		authorTitle: 'Parenting time calendar and custody schedule planning team',
		authorBio: 'CustodyBuilder creates plain-English custody schedule guides and calendar tools for parents comparing parenting time, printable schedules, and parenting plan language.',
		authorHref: '/about/',
		factCheckedDate: '2026-06-13',
		legalReviewerPlaceholder: 'Not yet reviewed by an attorney. This page is for educational planning only and should not be treated as legal advice.',
		disclaimer: 'This tool is for educational planning only and is not legal advice. Custody laws vary by state. Consult a qualified family law attorney or mediator for legal guidance.',
	},
	hero: {
		definition: 'A 5-2-2-5 custody schedule gives one parent a five-day block, the other parent a two-day block, then reverses the pattern so both parents receive equal time over two weeks.',
		bestFor: 'school-age children and parents who want one parent to carry a full school-week block while the other parent gets the weekend, then flip that pattern the next week.',
		proChips: ['Usually 50/50', 'Full school-week blocks', 'Alternating weekends', 'Easy two-week flip'],
		conChips: ['Five school nights apart', 'Weekend-only short blocks', 'Needs gear planning', 'Harder with distance'],
		ctas: [
			{ text: 'Generate my 5-2-2-5 calendar', href: '#schedule-generator', variant: 'primary' },
			{ text: 'Download printable schedule', href: '#printable-download', variant: 'secondary' },
			{ text: 'Compare custody schedules', href: '#comparison', variant: 'secondary' },
		],
	},
	atAGlanceTitle: '5-2-2-5 Custody Schedule Summary',
	atAGlance: [
		{ label: 'Parenting time', value: 'Usually 50/50' },
		{ label: 'Rotation length', value: 'Two-week cycle' },
		{ label: 'Exchanges', value: 'Usually fewer than 2-2-3' },
		{ label: 'Best for', value: 'School-age children and parents wanting longer blocks' },
		{ label: 'Weekend pattern', value: 'Alternating longer weekend blocks' },
		{ label: 'Common challenge', value: 'Longer stretches away from one parent' },
		{ label: 'Common use', value: 'Equal parenting plans' },
	],
	overview: [
		'The 5-2-2-5 custody schedule is best understood as a school-week-and-weekend flip. In the simple version shown here, Parent A has Monday through Friday in week one, Parent B has the weekend, then Parent B has Monday through Friday in week two and Parent A has the weekend. Over the full two-week cycle, each parent receives seven overnights, so it is usually grouped with other <a href="/50-50-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">50/50 custody schedules</a>.',
		'Families often choose 5-2-2-5 when they want fewer handoffs than a <a href="/2-2-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-3 custody schedule</a> and a calendar that lets one home carry a complete school-week routine at a time. The tradeoff is that the other parent’s two-day block may feel short and weekend-focused.',
		'The phrase 5-2-2-5 is sometimes used interchangeably with a <a href="/2-2-5-5-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-5-5 custody schedule</a>, but parents often mean different start points. On this page, 5-2-2-5 means the visible cycle starts with the five-day block, which makes the weekly flip easier to see.',
	],
	printableDownload: {
		title: 'Printable 5-2-2-5 Custody Schedule Downloads',
		description: 'Use the generator above to print or export the 5-day weekday block, 2-day weekend block version of this schedule. These cards point to existing generator and planning sections; no fake downloads are provided.',
		options: [
			{ title: 'Weekly schedule', description: 'Review how the Monday-through-Friday block and weekend block switch parents in the second week.', status: 'available', href: '#timeline' },
			{ title: 'Monthly calendar', description: 'Use the generator above to see where the five-day blocks land across partial weeks and month boundaries.', status: 'available', href: '#schedule-generator' },
			{ title: 'Yearly calendar', description: 'Export a yearly PDF to catch long runs where holidays or vacations interrupt the five-day weekday blocks.', status: 'available', href: '#schedule-generator' },
			{ title: 'Parenting plan worksheet', description: 'Use the sample clause below to define whether the five-day block starts after school, at daycare pickup, or at a fixed evening time.', status: 'available', href: '#parenting-plan-language' },
			{ title: 'Holiday planning worksheet', description: 'Use the holiday custody planner to decide when special days override the short two-day weekend blocks.', status: 'available', href: '/holiday-custody-planner/' },
		],
		ctas: [
			{ text: 'Generate printable calendar', href: '#schedule-generator', variant: 'primary' },
			{ text: 'Export PDF from the tool', href: '#schedule-generator', variant: 'secondary' },
			{ text: 'Plan holidays separately', href: '/holiday-custody-planner/', variant: 'secondary' },
		],
		yearOptions: ['Weekly schedule', 'Monthly PDF', 'Yearly PDF', 'Holiday worksheet'],
	},
	timeline: {
		title: 'How the 5-2-2-5 Schedule Works',
		description: 'This printable timeline shows the standard two-week 5-2-2-5 pattern. Some families describe the same rotation as 2-2-5-5 when they start the written schedule at a different point in the cycle.',
		weeks: [
			{
				label: 'Week 1',
				blocks: [
					{ parent: 'Parent A', days: 'Mon Tue Wed Thu Fri' },
					{ parent: 'Parent B', days: 'Sat Sun' },
				],
			},
			{
				label: 'Week 2',
				blocks: [
					{ parent: 'Parent B', days: 'Mon Tue Wed Thu Fri' },
					{ parent: 'Parent A', days: 'Sat Sun' },
				],
			},
		],
	},
	parentingPlanLanguage: {
		title: 'Sample 5-2-2-5 Parenting Plan Language',
		description: 'This plain-English sample shows how a 5-2-2-5 rotation can be described before it is adapted for a formal parenting plan.',
		clause: 'The parents will follow a repeating two-week 5-2-2-5 parenting schedule. In Week 1, Parent A will have parenting time from Monday after school or daycare through Saturday exchange, and Parent B will have parenting time from Saturday exchange through Monday school or daycare drop-off. In Week 2, Parent B will have parenting time from Monday after school or daycare through Saturday exchange, and Parent A will have parenting time from Saturday exchange through Monday school or daycare drop-off. This creates alternating five-day school-week blocks and alternating two-day weekend blocks. Holiday, school-break, vacation, birthday, Mother’s Day, Father’s Day, and special-day provisions will override the regular schedule when they apply.',
		disclaimer: 'This sample is educational only. Have any parenting plan language reviewed by a qualified family law professional before filing or signing.',
	},
	deepDiveSections: [
		{
			id: 'holidays-breaks-vacations',
			kicker: 'Special dates',
			title: 'Holidays, School Breaks, and Vacations',
			paragraphs: [
				'Holiday and vacation rules need extra clarity in a 5-2-2-5 plan because a holiday can interrupt either a full Monday-Friday block or the shorter weekend block. Parents should state whether the holiday pauses the regular cycle, replaces the affected days, or resumes with the next scheduled parent after the holiday ends.',
				'For this pattern, parents often write holiday rules around the block being interrupted: Thanksgiving may replace a short weekend block, winter break may split across both homes, and summer vacation may temporarily pause the Monday-Friday parent assignment. Use the <a href="/holiday-custody-planner/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">holiday custody planner</a> to map these exceptions before adding them to a <a href="/parenting-plan-template/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">parenting plan template</a>.',
			],
			items: [
				{ title: 'Thanksgiving', description: 'Often works best as a defined override because it can otherwise cut through the parent’s five-day weekday block.' },
				{ title: 'Christmas and winter break', description: 'Split the break into blocks so one parent is not limited to only the short weekend side of the rotation.' },
				{ title: 'Spring and summer breaks', description: 'Spring break may replace the entire school-week block; summer vacation often needs notice rules before the regular cycle resumes.' },
				{ title: 'Birthdays, Mother’s Day, and Father’s Day', description: 'Give these special days exact start and end times so they do not create confusion around the Saturday or Monday exchange.' },
			],
		},
		{
			id: 'exchange-times-locations',
			kicker: 'Exchanges',
			title: 'Exchange Times and Locations',
			paragraphs: [
				'In a 5-2-2-5 schedule, the most important handoffs are usually the start of the school-week block and the start or end of the weekend block. A clean Monday school or daycare drop-off can make the five-day block feel like a normal school week instead of a constant custody transition.',
				'Saturday or weekend exchanges need separate planning because they often happen outside school. Home exchanges can be simple for cooperative parents, while public-location exchanges may be better when weekend handoffs are tense. Evening exchanges should be used carefully so the child does not lose the first night of a five-day block to logistics.',
			],
			items: [
				{ title: 'School exchanges', description: 'Best for Monday transitions into a five-day block; less useful for Saturday handoffs or school breaks.' },
				{ title: 'Daycare exchanges', description: 'Useful when the five-day block starts on a care day; parents should confirm pickup authorization for both homes.' },
				{ title: 'Home exchanges', description: 'Convenient for weekend handoffs when boundaries are calm and the child’s belongings are ready.' },
				{ title: 'Public-location exchanges', description: 'Helpful for tense weekend handoffs, but travel time should not consume the short two-day block.' },
				{ title: 'Evening exchanges', description: 'Can fit work schedules, but avoid late starts that disrupt the first bedtime in the five-day block.' },
			],
		},
		{
			id: 'communication-tips',
			kicker: 'Co-parenting',
			title: 'Communication Tips for a 5-2-2-5 Schedule',
			paragraphs: [
				'The five-day block gives one home several school mornings in a row, so the departing parent should pass along homework status, activity gear, medication, upcoming appointments, and any school messages before the block begins. The short weekend block also needs clear packing because there is less time to recover from missing items.',
				'A shared calendar should mark which parent has the full school-week block and which parent has the weekend block. For planning conversations, use the <a href="/custody-percentage-calculator/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">custody percentage calculator</a> to review overnight totals and the <a href="/child-support-calculator/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">child support calculator</a> to understand support-planning questions that may come up before professional review.',
			],
			items: [
				{ title: 'Shared calendar', description: 'Mark the five-day school-week parent, weekend parent, activity transportation, and override dates.' },
				{ title: 'Child activities', description: 'Assign who handles weekday practices during the five-day block and weekend events during the two-day block.' },
				{ title: 'Homework coordination', description: 'Send assignment status before Monday transitions so the next home can carry the school week.' },
				{ title: 'Schedule changes', description: 'Define whether a changed weekend creates makeup time or simply resumes the next five-day block.' },
				{ title: 'Documenting changes', description: 'Keep written confirmations short, child-focused, and tied to the specific block being changed.' },
			],
		},
		{
			id: 'alternatives',
			kicker: 'Alternatives',
			title: 'Alternatives to 5-2-2-5',
			paragraphs: [
				'If 5-2-2-5 feels too long, compare a <a href="/2-2-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-3 custody schedule</a> for more frequent contact or a <a href="/3-4-4-3-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">3-4-4-3 custody schedule</a> for slightly shorter blocks. The <a href="/2-2-5-5-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">2-2-5-5 custody schedule</a> may be the same practical pattern with a different start point.',
				'Older children may prefer a <a href="/week-on-week-off-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">week-on/week-off custody schedule</a>. If equal time is not realistic, compare <a href="/60-40-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">60/40</a>, <a href="/70-30-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">70/30</a>, <a href="/80-20-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">80/20</a>, or <a href="/every-other-weekend-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">every other weekend</a> schedules.',
			],
		},
	],
	pros: [
		'Gives each parent a full school-week block in alternating weeks.',
		'Keeps the two-week cycle balanced at seven overnights per parent.',
		'Reduces the rapid handoff rhythm of 2-2-3 while still alternating weekends.',
		'Can make homework, uniforms, practices, and weekday transportation easier to assign for one week at a time.',
		'Makes short weekend blocks and long school-week blocks easy to spot on a printable custody calendar.',
	],
	cons: [
		'The parent on the two-day weekend block may have little school-week involvement that cycle.',
		'Five consecutive school nights can feel long for children who need frequent contact with both parents.',
		'Saturday or weekend exchanges require more planning because school cannot serve as the handoff point.',
		'The schedule can be misread as 2-2-5-5 unless the start day and exchange time are written clearly.',
		'It may be difficult when parents live far apart or when weekend activities require both homes to coordinate closely.',
	],
	example: {
		title: '5-2-2-5 Schedule Example',
		description: 'In a 5-2-2-5 schedule, the child may spend five weekdays with Parent A, a weekend with Parent B, five weekdays with Parent B, and a weekend with Parent A. The pattern repeats every two weeks and is easiest to understand on a calendar.',
		weeks: [
			{
				label: 'Week 1',
				blocks: [
					{ parent: 'Parent A', days: 'Mon Tue Wed Thu Fri' },
					{ parent: 'Parent B', days: 'Sat Sun' },
				],
			},
			{
				label: 'Week 2',
				blocks: [
					{ parent: 'Parent A', days: 'Mon Tue' },
					{ parent: 'Parent B', days: 'Wed Thu Fri Sat Sun' },
				],
			},
		],
	},
	comparison: {
		title: 'Compare 5-2-2-5 with other custody schedules',
		description: 'Use this table to compare 5-2-2-5 with common alternatives before choosing a custody calendar generator pattern or writing a parenting plan schedule.',
		columnLabels: {
			schedule: 'Schedule',
			bestFor: 'Best age group',
			exchangeFrequency: 'Exchanges',
			weekendPattern: 'Stability',
			notes: 'Pros',
		},
		rows: [
			{ schedule: '5-2-2-5', href: '/5-2-2-5-custody-schedule/', bestFor: 'School-age children who can handle one full school-week block in each home.', parentTimeSplit: 'Usually 50/50', exchangeFrequency: 'Usually fewer than 2-2-3', weekendPattern: 'Weekday block flips with the weekend block', notes: 'One parent manages the full school week, then the pattern flips.', cons: 'The short two-day block may feel weekend-only.', guideLabel: 'Current guide', badge: 'Current page' },
			{ schedule: '2-2-5-5', href: '/2-2-5-5-custody-schedule/', bestFor: 'Families wanting fixed weekdays and alternating five-day stretches.', parentTimeSplit: 'Usually 50/50', exchangeFrequency: '2-3 exchanges per week', weekendPattern: 'Same block lengths, different start point', notes: 'Can preserve fixed weekday responsibilities depending on how it is written.', cons: 'Can be confused with 5-2-2-5 unless the start day is clear.', guideLabel: '2-2-5-5 guide' },
			{ schedule: '2-2-3', href: '/2-2-3-custody-schedule/', bestFor: 'Younger children needing frequent contact.', parentTimeSplit: 'Usually 50/50', exchangeFrequency: '3-4 exchanges per week', weekendPattern: 'Moderate stability', notes: 'Shorter gaps between parents.', cons: 'More handoffs and coordination.', guideLabel: '2-2-3 guide' },
			{ schedule: '3-4-4-3', href: '/3-4-4-3-custody-schedule/', bestFor: 'Children who can handle three- and four-day blocks.', parentTimeSplit: 'Usually 50/50', exchangeFrequency: '2 exchanges per week', weekendPattern: 'Moderate to high stability', notes: 'Fewer transitions while keeping regular contact.', cons: 'Can be less intuitive at first.', guideLabel: '3-4-4-3 guide' },
			{ schedule: 'Week-on/week-off', href: '/week-on-week-off-custody-schedule/', bestFor: 'Older children and teens.', parentTimeSplit: 'Usually 50/50', exchangeFrequency: '1 exchange per week', weekendPattern: 'High stability', notes: 'Very simple calendar and fewer exchanges.', cons: 'A full week away may be too long.', guideLabel: 'Week-on/week-off guide' },
			{ schedule: 'Every other weekend', href: '/every-other-weekend-custody-schedule/', bestFor: 'Families where one home anchors most school-week routines.', parentTimeSplit: 'Often 80/20 to 85/15', exchangeFrequency: 'Usually every other weekend', weekendPattern: 'High primary-home stability', notes: 'Simple and low transition load.', cons: 'Much less weekday time for one parent.', guideLabel: 'Every other weekend guide' },
		],
		cta: {
			title: 'Compare other custody schedules',
			links: [
				{ title: '2-2-5-5 custody schedule', slug: '2-2-5-5-custody-schedule', description: 'Compare the same block lengths when the written cycle starts with the two-day blocks.' },
				{ title: '2-2-3 custody schedule', slug: '2-2-3-custody-schedule', description: 'Review shorter blocks and more frequent parent contact.' },
				{ title: '3-4-4-3 custody schedule', slug: '3-4-4-3-custody-schedule', description: 'Compare another 50/50 schedule with three- and four-day blocks.' },
				{ title: 'Week-on/week-off custody schedule', slug: 'week-on-week-off-custody-schedule', description: 'See whether full weeks fit older children better.' },
				{ title: 'Every other weekend schedule', slug: 'every-other-weekend-custody-schedule', description: 'Compare a lower-transition schedule when 50/50 is not realistic.' },
			],
		},
	},
	faq: [
		{ question: 'What is a 5-2-2-5 custody schedule?', answer: 'A 5-2-2-5 custody schedule is a repeating two-week plan that starts with a five-day block, then a two-day block, then a two-day block, then a five-day block. On a school calendar, that often looks like one parent handling Monday through Friday, the other parent taking the weekend, and then the roles flipping the next week.' },
		{ question: 'Is 5-2-2-5 the same as 2-2-5-5?', answer: 'They use the same block lengths, but 5-2-2-5 starts the written pattern with the five-day block. That distinction matters when parents are trying to describe who carries the full school week and who starts with the weekend block.', answerHtml: 'They use the same block lengths, but 5-2-2-5 starts the written pattern with the five-day block. That distinction matters when parents are trying to describe who carries the full school week and who starts with the weekend block. Compare the <a href="/2-2-5-5-custody-schedule/" class="text-accent hover:underline">2-2-5-5 custody schedule</a> if your written cycle starts with the two-day blocks.' },
		{ question: 'Is 5-2-2-5 always 50/50?', answer: 'The standard version is usually 50/50 because each parent receives one five-day block and one two-day block in every two-week cycle. The annual number can still shift if holidays, vacations, or summer blocks override the regular pattern.' },
		{ question: 'Is 5-2-2-5 better than 2-2-3?', answer: '5-2-2-5 may be better when one home can carry a full school week and the child benefits from fewer handoffs. 2-2-3 may be better when the child needs shorter gaps between parents and more frequent contact.', answerHtml: '5-2-2-5 may be better when one home can carry a full school week and the child benefits from fewer handoffs. A <a href="/2-2-3-custody-schedule/" class="text-accent hover:underline">2-2-3 custody schedule</a> may be better when the child needs shorter gaps between parents and more frequent contact.' },
		{ question: 'Is this schedule good for toddlers?', answer: 'It is often harder for toddlers than shorter rotations because five consecutive nights can be a long separation. It may work only when both homes already have strong routines and the child transitions calmly after longer blocks.' },
		{ question: 'Is this schedule good for school-age children?', answer: 'It can be a strong school-age option when each parent can handle a complete school-week block. The key question is whether homework, uniforms, lunches, practices, and transportation can stay organized for a full Monday-Friday stretch.' },
		{ question: 'Is this schedule good for teenagers?', answer: 'It can work for teenagers who want fewer midweek handoffs, but the weekend-only short block may conflict with jobs, sports, friends, or driving plans. Some teens may still prefer week-on/week-off because it is easier to remember.', answerHtml: 'It can work for teenagers who want fewer midweek handoffs, but the weekend-only short block may conflict with jobs, sports, friends, or driving plans. Some teens may still prefer <a href="/week-on-week-off-custody-schedule/" class="text-accent hover:underline">week-on/week-off custody</a> because it is easier to remember.' },
		{ question: 'How many exchanges does it require?', answer: 'The number depends on the exact exchange time, but the defining feature is that exchanges are clustered around the end of the five-day school-week block and the short weekend block. It usually feels less busy than 2-2-3 because the child is not changing homes every two or three days.' },
		{ question: 'How are holidays handled?', answer: 'Holiday rules should say what happens when a holiday interrupts a five-day school-week block versus a two-day weekend block. Without that detail, one parent may lose most of a short weekend block to a holiday override.', answerHtml: 'Holiday rules should say what happens when a holiday interrupts a five-day school-week block versus a two-day weekend block. Without that detail, one parent may lose most of a short weekend block to a holiday override. The <a href="/holiday-custody-planner/" class="text-accent hover:underline">holiday custody planner</a> can help map those exceptions.' },
		{ question: 'How are vacations handled?', answer: 'Vacation rules should define whether a vacation may replace an entire five-day block, a short weekend block, or both. The plan should also say how much notice is required and whether the regular pattern resumes or shifts after the vacation.' },
		{ question: 'Can this schedule affect child support?', answer: 'The schedule is usually 50/50 by overnights, but support questions can still depend on state law, income, expenses, and the exact annual calendar after holidays and vacations are added.', answerHtml: 'The schedule is usually 50/50 by overnights, but support questions can still depend on state law, income, expenses, and the exact annual calendar after holidays and vacations are added. Use the <a href="/child-support-calculator/" class="text-accent hover:underline">child support calculator</a> and <a href="/custody-percentage-calculator/" class="text-accent hover:underline">custody percentage calculator</a> as educational planning tools.' },
		{ question: 'What if parents live far apart?', answer: 'The full school-week block can reduce midweek driving, but the child still needs reliable transportation at the weekend exchange. If weekend travel is long or activities are split between towns, a less even schedule may be more realistic.', answerHtml: 'The full school-week block can reduce midweek driving, but the child still needs reliable transportation at the weekend exchange. If weekend travel is long or activities are split between towns, compare <a href="/60-40-custody-schedule/" class="text-accent hover:underline">60/40</a>, <a href="/70-30-custody-schedule/" class="text-accent hover:underline">70/30</a>, <a href="/80-20-custody-schedule/" class="text-accent hover:underline">80/20</a>, or <a href="/every-other-weekend-custody-schedule/" class="text-accent hover:underline">every other weekend</a> schedules.' },
		{ question: 'Can parents customize it?', answer: 'Yes. Parents can customize the start day, exchange time, holiday overrides, vacation rules, and makeup-time terms. The most important detail is writing exactly when the five-day block begins and ends.' },
		{ question: 'Can siblings use the same schedule?', answer: 'Siblings can use the same 5-2-2-5 pattern when one calendar helps school and activity logistics. Different ages may still require separate notes for transportation, childcare, devices, homework, or sports gear.' },
		{ question: 'Is it court-approved?', answer: 'A court may approve a 5-2-2-5 schedule if the full plan meets local legal standards and supports the child’s best interests. The rotation itself is only one part of the order; exchange terms, holidays, decision-making, and transportation also matter.' },
		{ question: 'Can I use this schedule in a parenting plan?', answer: 'You can use 5-2-2-5 as a starting point, but the plan should clearly define when the five-day block starts, when the weekend block starts, what happens after holidays, and how parents document changes.', answerHtml: 'You can use 5-2-2-5 as a starting point, but the plan should clearly define when the five-day block starts, when the weekend block starts, what happens after holidays, and how parents document changes. Start with a <a href="/parenting-plan-template/" class="text-accent hover:underline">parenting plan template</a> and review it with a qualified professional.' },
	],
	relatedSchedules: [
		'2-2-3-custody-schedule',
		'2-2-5-5-custody-schedule',
		'3-4-4-3-custody-schedule',
		'week-on-week-off-custody-schedule',
		'60-40-custody-schedule',
		'every-other-weekend-custody-schedule',
		'50-50-custody-schedule',
	],
	relatedTools: [
		{ title: 'Parenting Plan Template', slug: 'parenting-plan-template', description: 'Turn your 5-2-2-5 parenting schedule into written parenting plan terms.' },
		{ title: 'Custody Percentage Calculator', slug: 'custody-percentage-calculator', description: 'Estimate parenting time percentages from overnight totals.' },
		{ title: 'Child Support Calculator', slug: 'child-support-calculator', description: 'Review support-planning questions alongside custody schedule decisions.' },
	],
	relatedHeading: 'Related 5-2-2-5 custody schedule tools',
	relatedLinks: [
		{ title: '2-2-5-5 custody schedule', slug: '2-2-5-5-custody-schedule', description: 'Compare the two-day-first version of this rotation and how it changes weekday assignments.' },
		{ title: '2-2-3 custody schedule', slug: '2-2-3-custody-schedule', description: 'Review a shorter-block 50/50 schedule with more frequent contact.' },
		{ title: '3-4-4-3 custody schedule', slug: '3-4-4-3-custody-schedule', description: 'Compare another 50/50 option with three- and four-day blocks.' },
		{ title: 'Week-on/week-off custody schedule', slug: 'week-on-week-off-custody-schedule', description: 'See whether full-week blocks fit older children better.' },
		{ title: '50/50 custody schedules', slug: '50-50-custody-schedule', description: 'Compare common equal parenting time options.' },
		{ title: 'Holiday custody planner', slug: 'holiday-custody-planner', description: 'Plan holidays, school breaks, birthdays, and vacations separately.' },
		{ title: 'Parenting plan template', slug: 'parenting-plan-template', description: 'Write exchange, holiday, vacation, and schedule-change terms.' },
		{ title: 'Custody percentage calculator', slug: 'custody-percentage-calculator', description: 'Calculate overnight percentages from the calendar.' },
	],
	article: {
		headline: '5-2-2-5 Custody Schedule',
		authorName: 'CustodyBuilder Editorial Team',
		reviewerName: 'CustodyBuilder Editorial Team',
		datePublished: '2026-06-13',
		dateModified: '2026-06-13',
	},
};

export default schedule;
