import type { ScheduleContent } from './types';

const schedule: ScheduleContent = {
	id: '70-30',
	title: '70/30 Custody Schedule',
	slug: '70-30-custody-schedule',
	description: 'Understand when a 70/30 parenting-time arrangement makes sense, how it affects school routines, transportation, child support, and parenting plan decisions.',
	metaTitle: '70/30 Custody Schedule Guide | Primary Parent Planning',
	metaDescription: 'Learn when 70/30 custody makes sense, how many overnights it means, child support considerations, school stability, transportation, holidays, and parenting plan language.',
	canonicalUrl: 'https://custodybuilder.com/70-30-custody-schedule/',
	lastUpdated: '2026-06-13',
	lede: 'A 70/30 custody arrangement gives one parent a clear majority of overnights while preserving regular, meaningful parenting time for the other parent. This guide focuses on when 70/30 makes sense, not just what the calendar pattern looks like.',
	trust: {
		reviewerLabel: 'Reviewed for clarity by',
		reviewerName: 'CustodyBuilder Editorial Team',
		reviewerCredential: 'Reviewed for clarity, parenting-time math, and practical planning usefulness by the CustodyBuilder Editorial Team.',
		reviewerHref: '/about/',
		authorName: 'CustodyBuilder Editorial Team',
		authorTitle: 'Parenting time calendar and custody schedule planning team',
		authorBio: 'CustodyBuilder creates plain-English custody schedule guides and calendar tools for parents comparing parenting time, overnights, printable calendars, and parenting plan options.',
		authorHref: '/about/',
		factCheckedDate: '2026-06-13',
		legalReviewerPlaceholder: 'Not yet reviewed by an attorney. This page is for educational planning only and should not be treated as legal advice.',
		disclaimer: 'This guide is for educational planning only and is not legal advice. Custody laws, child support rules, and court practices vary by state. Consult a qualified family law attorney or mediator for legal guidance.',
	},
	hero: {
		definition: 'A 70/30 custody schedule usually means one parent has about 256 overnights per year and the other has about 109, but the real purpose is often a stable primary-home structure.',
		bestFor: 'families that need one parent to anchor school routines while the other parent keeps predictable, recurring parenting time.',
		proChips: ['Primary-home stability', 'Regular secondary-parent time', 'Lower exchange load', 'Useful with distance'],
		conChips: ['Support may change', 'Weekday involvement can shrink', 'Needs transportation rules', 'Must protect relationship time'],
		ctas: [
			{ text: 'Test a 70/30 calendar', href: '#schedule-generator', variant: 'primary' },
			{ text: 'Compare percentages', href: '#percentage-matrix', variant: 'secondary' },
			{ text: 'Plan support impact', href: '#child-support', variant: 'secondary' },
		],
	},
	atAGlanceTitle: '70/30 Custody At a Glance',
	atAGlance: [
		{ label: 'Parenting time split', value: 'About 70% / 30% by overnights' },
		{ label: 'Typical overnights', value: 'About 256 and 109 per year' },
		{ label: 'Primary-parent arrangement', value: 'One home usually anchors school-week routines' },
		{ label: 'Child support implications', value: 'Often more significant than 50/50 or 60/40; rules vary by state' },
		{ label: 'School stability level', value: 'High when the primary home manages weekday logistics well' },
		{ label: 'Exchange frequency', value: 'Usually lower than shared rotations, but depends on the plan' },
		{ label: 'Best fit families', value: 'Distance, uneven work schedules, school-centered routines, or frequent travel' },
		{ label: 'Common challenges', value: 'Maintaining weekday connection for the 30% parent and sharing school information' },
		{ label: 'Typical use cases', value: 'Primary residence plans, expanded weekend time, or a step between 60/40 and 80/20' },
	],
	overviewTitle: 'When Does a 70/30 Custody Arrangement Make Sense?',
	overview: [
		'A 70/30 custody arrangement is a parenting-time allocation where one parent has a stronger majority of overnights and usually more daily responsibility. It often makes sense when a child needs one consistent school-week home, parents live far enough apart that frequent exchanges are stressful, or one parent work schedule makes equal weekday time unreliable.',
		'This is different from a <a href="/50-50-custody-schedule/" class="text-accent underline decoration-line underline-offset-4 hover:text-primary">50/50 custody schedule</a> decision. The main question is not which equal-time rotation looks best. The question is whether a primary-parent structure better protects school, sleep, transportation, activities, and stable routines while still preserving a meaningful relationship with the other parent.',
		'Many 70/30 plans use weekend blocks, weekday overnights, extended school breaks, holiday time, or summer parenting time to keep the lower-time parent involved. The strongest plans describe responsibilities, not only percentages.',
	],
	printableDownload: {
		title: 'Printable 70/30 Planning Resources',
		description: 'These are educational planning cards, not fake downloads. Use them as prompts while testing the live calendar and drafting a parenting plan.',
		options: [
			{ title: '70/30 parenting worksheet', description: 'List why a primary-parent arrangement is needed and how the 30% parent stays involved.', status: 'available', href: '#when-70-30-works' },
			{ title: 'Custody planning checklist', description: 'Review support, school, transportation, holidays, and communication before choosing 70/30.', status: 'available', href: '#decision-summary' },
			{ title: 'School-year planning worksheet', description: 'Plan homework, attendance, school communication, and activity logistics around the primary home.', status: 'available', href: '#school-stability' },
			{ title: 'Holiday planning worksheet', description: 'Use the holiday planner to protect special-day time for both parents.', status: 'available', href: '/holiday-custody-schedule/' },
			{ title: 'Transportation planning worksheet', description: 'Define pickup duties, exchange locations, travel cost expectations, and backup plans.', status: 'available', href: '#transportation-logistics' },
		],
		ctas: [
			{ text: 'Generate a 70/30 calendar', href: '#schedule-generator', variant: 'primary' },
			{ text: 'Calculate parenting time', href: '/custody-percentage-calculator/', variant: 'secondary' },
			{ text: 'Plan holidays separately', href: '/holiday-custody-schedule/', variant: 'secondary' },
		],
		yearOptions: ['70/30 worksheet', 'School-year worksheet', 'Holiday worksheet', 'Transportation worksheet'],
	},
	howItWorks: {
		title: 'How a 70/30 Parenting-Time Allocation Works',
		description: [
			'A 70/30 plan usually gives the primary parent most school-night overnights and ordinary weekday responsibility. The other parent may have consistent weekends, a weekday overnight, extended breaks, summer blocks, or a repeating block schedule depending on distance and availability.',
			'The live calendar estimates overnights. Daytime visits, calls, school events, activity attendance, and parent communication still matter, but they do not change the overnight percentage unless another overnight is added.',
		],
	},
	pros: [
		'Creates one primary school-week home when children need routine consistency.',
		'Can reduce frequent exchanges when parents live 30-60 minutes apart or farther.',
		'Gives the lower-time parent recurring overnights without forcing equal-time logistics.',
		'Can work as a step up from every other weekend or a step down from an impractical 60/40 or 50/50 plan.',
		'Helps clarify who manages ordinary weekday tasks when parents have very different schedules.',
	],
	cons: [
		'The 30% parent may lose ordinary weekday involvement unless the plan intentionally protects it.',
		'Child support may be affected more than in near-equal arrangements.',
		'The primary parent can carry a heavy school, transportation, homework, and appointment workload.',
		'Weekend-heavy plans can make one parent feel like the fun parent and the other like the routine parent.',
		'Children may outgrow the arrangement as school, activities, driving, or parent availability changes.',
	],
	example: {
		title: 'Example 70/30 Parenting-Time Structure',
		description: 'This example shows the allocation idea, not a one-size-fits-all pattern. Parent A anchors the school week while Parent B has reliable weekend or block time. Use the generator to test exact dates and overnight totals.',
		weeks: [
			{
				label: 'Primary-home responsibilities',
				blocks: [
					{ parent: 'Parent A', days: 'School mornings, homework systems, weekday appointments' },
					{ parent: 'Parent B', days: 'Recurring overnights, activity attendance, calls, holiday blocks' },
				],
			},
			{
				label: 'Planning questions',
				blocks: [
					{ parent: 'Calculate', days: 'Annual overnights after holidays and summer' },
					{ parent: 'Write down', days: 'Transportation, communication, and review rules' },
				],
			},
		],
	},
	comparison: {
		title: '70/30 vs Other Parenting Time Arrangements',
		description: 'Compare 70/30 with nearby parenting-time allocations by practical effect, not just percentage. The right option depends on school stability, travel, parent availability, and how much weekday involvement both parents can realistically support.',
		columnLabels: {
			schedule: 'Arrangement',
			bestFor: 'Common use cases',
			exchangeFrequency: 'Exchange frequency',
			weekendPattern: 'School stability',
			notes: 'Child support impact',
		},
		rows: [
			{ schedule: '50/50', href: '/50-50-custody-schedule/', bestFor: 'Both homes can support school, activities, and transportation consistently.', parentTimeSplit: 'About 50% / 50%', exchangeFrequency: 'Varies by rotation', weekendPattern: 'Shared school responsibility if logistics are strong', notes: 'Support may still apply, but overnight split is closer to equal.', cons: 'Can fail when distance or work schedules make equal school weeks unrealistic.', guideLabel: 'Compare 50/50' },
			{ schedule: '60/40', href: '/60-40-custody-schedule/', bestFor: 'One home anchors slightly more school time while both parents keep substantial overnights.', parentTimeSplit: 'About 60% / 40%', exchangeFrequency: 'Moderate', weekendPattern: 'Moderate primary-home structure', notes: 'Often less support impact than 70/30, but state rules vary.', cons: 'May not solve logistics if one home needs a much stronger weekday anchor.', guideLabel: 'Compare 60/40' },
			{ schedule: '70/30', href: '/70-30-custody-schedule/', bestFor: 'Primary-home routines with predictable recurring time for the other parent.', parentTimeSplit: 'About 70% / 30%', exchangeFrequency: 'Usually lower than 50/50 or 60/40', weekendPattern: 'High school stability when primary duties are clear', notes: 'Parenting time is only one factor used in support calculations.', cons: 'Lower-time parent needs intentional school and activity involvement.', guideLabel: 'Current guide', badge: 'Current page' },
			{ schedule: '80/20', href: '/80-20-custody-schedule/', bestFor: 'Greater distance, limited availability, or a stronger primary-home structure.', parentTimeSplit: 'About 80% / 20%', exchangeFrequency: 'Lower', weekendPattern: 'Very high primary-home consistency', notes: 'Support impact may be more pronounced than 70/30 depending on rules.', cons: 'Longer gaps and less weekday participation for the lower-time parent.', guideLabel: 'Compare 80/20' },
			{ schedule: 'Every other weekend', href: '/every-other-weekend-custody-schedule/', bestFor: 'Traditional weekend parenting time, long distance, or limited school-week availability.', parentTimeSplit: 'Often lower than 70/30 unless extra time is added', exchangeFrequency: 'Usually every other weekend', weekendPattern: 'Primary home carries most school duties', notes: 'May need holiday, summer, or weekday overnights to approach 70/30.', cons: 'Can create long gaps between overnights.', guideLabel: 'Compare weekends' },
		],
	},
	decisionGuide: {
		quickAnswer: {
			title: 'Quick Answer',
			description: 'A 70/30 custody arrangement usually makes sense when one home needs to be the practical school-week anchor, but the other parent should still have regular and meaningful overnight time.',
			items: [
				{ label: 'Works well when', title: 'School stability needs one lead home', href: '#school-stability' },
				{ label: 'Often helps when', title: 'Parents live 30-60 minutes apart', href: '#transportation-logistics' },
				{ label: 'Often helps when', title: 'Work travel makes equal time unreliable', href: '#schedule-examples' },
				{ label: 'Compare first if', title: '60/40 might be enough structure', href: '/60-40-custody-schedule/' },
				{ label: 'Compare if more structure is needed', title: '80/20 custody schedule', href: '/80-20-custody-schedule/' },
			],
		},
		whenWorksBest: {
			title: 'Is a 70/30 Custody Schedule Right for Your Family?',
			rows: [
				{ situation: 'Homes are 30-60 minutes apart', why: 'One primary school-week home can reduce rushed mornings, long drives, and activity conflicts.', watchFor: 'The 30% parent may need longer weekend blocks, calls, or activity involvement to stay connected.' },
				{ situation: 'Children attend school near one parent', why: 'The school-near parent can handle attendance, lunch, homework, and transportation with fewer disruptions.', watchFor: 'School communication should still be shared with the other parent.' },
				{ situation: 'Work schedules are uneven', why: 'A parent with more predictable weekday availability can anchor school nights while the other parent keeps reliable blocks.', watchFor: 'Travel, overtime, and backup-care rules need written notice requirements.' },
				{ situation: 'Extracurricular logistics are heavy', why: 'Sports, tutoring, therapy, music, or travel teams may need one parent to coordinate weekly details.', watchFor: 'The non-primary parent should still receive schedules, gear lists, and event information.' },
				{ situation: 'The child needs routine consistency', why: 'Some children do better with fewer school-week exchanges and one consistent homework/bedtime structure.', watchFor: 'Stability should not become isolation from the other parent.' },
			],
		},
		percentageMatrix: {
			title: '70/30 Compared With Nearby Parenting Time Splits',
			rows: [
				{ schedule: '50/50', href: '/50-50-custody-schedule/', badge: 'Equal-time option', parentA: 'About 50%', parentB: 'About 50%', bestFor: 'Both homes can manage weekday routines and transportation', stability: 'Shared if logistics are strong', exchangeFrequency: 'Often higher' },
				{ schedule: '60/40', href: '/60-40-custody-schedule/', badge: 'Less primary-home structure', parentA: 'About 60%', parentB: 'About 40%', bestFor: 'A modest school-week anchor with substantial time in both homes', stability: 'Moderate to high', exchangeFrequency: 'Moderate' },
				{ schedule: '70/30', href: '/70-30-custody-schedule/', badge: 'Primary-parent planning focus', parentA: 'About 70%', parentB: 'About 30%', bestFor: 'Primary school-week home with recurring, meaningful time for the other parent', stability: 'High when responsibilities are clear', exchangeFrequency: 'Lower' },
				{ schedule: '80/20', href: '/80-20-custody-schedule/', badge: 'Stronger primary-home structure', parentA: 'About 80%', parentB: 'About 20%', bestFor: 'Long distance, limited availability, or traditional visitation patterns', stability: 'Very high for one home', exchangeFrequency: 'Lowest' },
			],
		},
		scheduleCards: {
			title: 'When Families Choose 70/30',
			description: 'These real-world scenarios show why families choose a 70/30 allocation instead of forcing a shared rotation or reducing time too far.',
			items: [
				{ title: 'Parents 30-60 minutes apart', badge: 'Distance', bestFor: 'Families where school-week driving is possible occasionally but too hard several times each week.', pros: ['Protects school mornings', 'Reduces rushed commutes', 'Keeps recurring time for both parents'], watchOutFor: 'Transportation cost and pickup duties need clear rules.', complexity: 'Medium' },
				{ title: 'Demanding work schedules', badge: 'Work', bestFor: 'A parent travels, works rotating shifts, or has unpredictable overtime while the other parent has stable weekdays.', pros: ['Avoids repeated failed exchanges', 'Supports reliable supervision', 'Can include review points'], watchOutFor: 'The plan should not turn work constraints into vague make-up time.', complexity: 'Medium' },
				{ title: 'School-centered routines', badge: 'School', bestFor: 'Children who need one home to anchor homework, attendance, transportation, supplies, and bedtime.', pros: ['Consistent weekday structure', 'Clear school communication lead', 'Fewer misplaced school items'], watchOutFor: 'The other parent still needs access to school information.', complexity: 'Low' },
				{ title: 'Frequent parent travel', badge: 'Travel', bestFor: 'A parent can provide meaningful blocks but cannot promise recurring school-week availability.', pros: ['Uses available blocks honestly', 'Can protect advance notice', 'Avoids unreliable equal time'], watchOutFor: 'Travel schedules should be shared early enough to protect the child routine.', complexity: 'High' },
				{ title: 'Blended family logistics', badge: 'Household', bestFor: 'Step-sibling schedules, childcare availability, or shared transportation make one home better suited for school weeks.', pros: ['Can simplify household coordination', 'Supports sibling/activity planning', 'Reduces last-minute changes'], watchOutFor: 'The child should not feel like logistics are valued over relationships.', complexity: 'Medium' },
				{ title: 'Teen schedules', badge: 'Teen', bestFor: 'Teenagers with jobs, sports, driving, exams, or social commitments who need fewer school-week disruptions.', pros: ['Allows routine and independence', 'Can include flexible blocks', 'Supports activity participation'], watchOutFor: 'Teen input helps, but adults should keep boundaries and safety rules.', complexity: 'Medium' },
			],
		},
		mistakes: {
			title: 'Common 70/30 Custody Mistakes',
			items: [
				{ title: 'Unclear transportation rules', problem: 'The plan states the percentage but not who drives, where exchanges happen, or who covers long-distance travel.', why: 'Transportation is often where 70/30 plans fail first because one parent may carry most school-week logistics.', betterApproach: 'Define pickup duties, exchange locations, backup drivers, late-pickup notice, and travel cost expectations.' },
				{ title: 'Inconsistent exchange times', problem: 'Weekend or weekday handoffs shift from week to week without a written rule.', why: 'Unpredictable exchanges can disrupt sleep, activities, homework, and parent work schedules.', betterApproach: 'Use school pickup, after-school windows, or fixed evening times whenever possible.' },
				{ title: 'Poor school communication', problem: 'The primary parent receives most school information and the other parent misses updates.', why: 'The 30% parent may become disconnected from grades, assignments, events, and teacher communication.', betterApproach: 'Share portal access, calendars, teacher emails, activity schedules, and urgent school updates.' },
				{ title: 'Ignoring activity schedules', problem: 'The plan gives weekend or block time but does not handle practices, tournaments, recitals, or tutoring.', why: 'Activities can control the real calendar more than the overnight percentage.', betterApproach: 'Assign transportation, gear, fees, schedule updates, and attendance expectations.' },
				{ title: 'Never revisiting the plan', problem: 'A schedule that worked at age six remains unchanged even after school, work, or teen needs change.', why: 'Children grow, activities expand, and parent availability changes.', betterApproach: 'Add review points tied to school transitions, relocation, work changes, or major activity changes.' },
			],
		},
		ageApproach: {
			title: 'Is 70/30 Appropriate by Age?',
			description: 'The age question is not just “how many overnights.” It is whether the child benefits more from stable routines or from a more balanced parenting-time split at this stage.',
			rows: [
				{ age: 'Toddlers', recommended: 'Routine-focused 70/30 only with frequent connection', guideHref: '/best-custody-schedule-for-toddler/', reason: 'Toddlers may need consistent sleep and caregiving rhythms, but long gaps from the 30% parent can be hard unless contact is frequent and calm.' },
				{ age: 'Preschoolers', recommended: 'Shorter blocks with a strong primary routine', reason: 'A primary home can help with bedtime and preschool routines, but the other parent should have predictable overnights or visits.' },
				{ age: 'Elementary school', recommended: 'Often the strongest 70/30 fit', guideHref: '/best-custody-schedule-for-7-year-old/', reason: 'School transportation, homework, lunch, reading logs, and activities may benefit from one weekday anchor.' },
				{ age: 'Middle school', recommended: 'Activity-aware 70/30', reason: 'Sports, clubs, devices, homework, and friendships require coordination between both homes even if one home carries more school nights.' },
				{ age: 'Teenagers', recommended: 'Flexible 70/30 with teen logistics considered', guideHref: '/best-custody-schedule-for-teenager/', reason: 'Teen jobs, driving, practices, social plans, and exams may make 70/30 practical, but the teen should not be responsible for managing parent conflict.' },
			],
		},
		holidayOverride: {
			title: 'Holidays, School Breaks, and Vacations in a 70/30 Arrangement',
			description: [
				'In a 70/30 plan, holidays and breaks are not only percentage math. They are also a way to preserve parent relationships when one parent has fewer ordinary school-week overnights.',
				'Parents often alternate major holidays, split winter break, rotate spring break, add summer blocks, or give travel windows to the 30% parent. The plan should say whether these overnights count toward the annual split or override the regular allocation.',
			],
			rows: [
				{ scenario: 'Thanksgiving and winter break', normalSchedule: 'The primary parent may normally have most school-week nights.', holidayExample: 'Alternating or splitting the break can give the 30% parent meaningful tradition time.' },
				{ scenario: 'Summer schedule', normalSchedule: 'The school-year rhythm may be primary-home focused.', holidayExample: 'A longer summer block can increase relationship time without disrupting school attendance.' },
				{ scenario: 'Travel planning', normalSchedule: 'The lower-time parent may need longer blocks for trips.', holidayExample: 'The plan should define notice, itinerary sharing, passport rules, and return times.' },
				{ scenario: 'Relationship preservation', normalSchedule: 'The regular calendar may limit weekday involvement.', holidayExample: 'Special days, school breaks, and activities can help prevent the 30% parent from becoming weekend-only.' },
			],
		},
		logistics: {
			title: 'Transportation and Exchange Planning',
			description: [
				'Transportation rules matter more in 70/30 than many parents expect. Because one parent often handles most school-week logistics, unclear pickup duties can create resentment or repeated conflict.',
				'A strong 70/30 plan defines who picks up, who drops off, where exchanges happen, what happens when a parent is late, how long-distance travel is shared, and how parents reduce direct conflict during handoffs.',
			],
			items: [
				'Use school exchanges when they reduce direct conflict and protect the child routine',
				'Define whether the receiving parent picks up or the ending parent drops off',
				'Plan weekend exchanges around practices, games, work shifts, and travel time',
				'Use neutral public locations when home exchanges create conflict',
				'Write backup-driver and late-notice expectations into the parenting plan',
				'Clarify travel cost sharing when distance is a main reason for 70/30',
			],
		},
		commonStart: {
			title: 'How 70/30 Can Support School Stability',
			description: [
				'The strongest reason to choose 70/30 is often school stability. One home may be closer to school, better able to manage morning transportation, or more available for homework, appointments, lunch, devices, and school communication.',
				'That does not mean the other parent becomes uninvolved. A strong plan gives the 30% parent access to school portals, calendars, activities, teacher communication, and special events. The child should experience one stable school rhythm without losing the other parent’s involvement.',
				'Before choosing 70/30, test the real school week: drop-off time, pickup time, homework, activities, therapy, tutoring, school supplies, and bedtime. If a near-equal plan repeatedly fails this test, 70/30 may be more child-focused.',
			],
		},
		insight: {
			title: 'Life as the Primary Parent in a 70/30 Schedule',
			description: [
				'The primary parent in a 70/30 schedule often becomes the default manager for school communication, appointments, transportation, activity schedules, homework oversight, and routine consistency. That role can be stabilizing for the child, but it can also become heavy if responsibilities are not acknowledged.',
				'The parenting plan should avoid vague assumptions. It should say who receives school notices, who schedules appointments, how costs are shared, who transports to activities, and how the other parent receives updates. The 30% parent can still attend conferences, activities, medical appointments, and school events even with fewer overnights.',
			],
		},
		childSupport: {
			title: 'How a 70/30 Custody Schedule May Affect Child Support',
			description: [
				'Parenting time is only one factor used in support calculations. A 70/30 schedule often affects support differently than a 50/50 or 60/40 arrangement because one parent has substantially more overnights and may carry more daily expenses.',
				'Support rules vary by state. Common factors may include parent income, annual overnights, healthcare costs, childcare expenses, extracurricular costs, travel expenses, other supported children, and whether guideline formulas adjust for parenting time.',
				'Do not assume that 70/30 automatically creates a specific support result. Use the calendar to understand overnights, then compare that information with a child support calculator, parenting time calculator, custody percentage calculator, or local professional guidance.',
			],
			factors: ['Parenting time is only one factor', 'State guideline differences', 'Annual overnights', 'Parent income', 'Healthcare costs', 'Childcare expenses', 'Extracurricular costs', 'Travel expenses'],
			ctaText: 'Estimate Texas Child Support',
		},
		shiftLater: {
			title: 'Transitioning Into a 70/30 Schedule',
			description: [
				'Families move into 70/30 for different reasons. Some increase time from every other weekend or 80/20 because the lower-time parent can now handle more overnights. Others move down from 60/40 or 50/50 because school, distance, work schedules, or child needs make a more primary-home structure healthier.',
				'The cleanest transitions use a trial period and review points. Parents can test a school month, a semester, or a summer block before making the allocation permanent. The plan should explain what success looks like and what happens if the child struggles.',
			],
			reviewPoints: [
				'Every other weekend to 70/30: add regular overnights or longer school-break blocks',
				'80/20 to 70/30: increase the lower-time parent’s recurring time when reliability improves',
				'60/40 to 70/30: reduce exchanges when school-week logistics are still strained',
				'50/50 to 70/30: move to a primary-home structure when equal time repeatedly fails',
				'Review after school changes, relocation, work changes, or major activity changes',
			],
			ctaText: 'Draft transition terms',
		},
		decisionSummary: {
			title: 'If You Read Only One Thing',
			description: [
				'Choose 70/30 when it solves a real parenting problem: school stability, distance, transportation, work travel, activity logistics, or a child need for one consistent weekday home.',
				'Do not choose 70/30 only because it sounds like a compromise. The plan should protect the primary-home routine while giving the 30% parent meaningful, predictable, and relationship-preserving time.',
			],
			primaryCta: { text: 'Test a 70/30 calendar', href: '#schedule-generator' },
			secondaryCta: { text: 'Calculate parenting time', href: '/custody-percentage-calculator/' },
		},
		ctaHub: {
			title: 'Plan Your 70/30 Parenting Arrangement',
			items: [
				{ title: 'Child Support Calculator', slug: 'texas-child-support-calculator', description: 'Review support planning after you understand income, expenses, and parenting time.' },
				{ title: 'Custody Percentage Calculator', slug: 'custody-percentage-calculator', description: 'Check annual overnights after holidays, school breaks, and summer blocks.' },
				{ title: 'Parenting Time Calculator', slug: 'custody-percentage-calculator', description: 'Compare 70/30 with nearby percentage arrangements before finalizing terms.' },
				{ title: 'Parenting Plan Template', slug: 'parenting-plan-template', description: 'Document primary residence, exchanges, transportation, holidays, and review points.' },
				{ title: 'Holiday Custody Planner', slug: 'holiday-custody-schedule', description: 'Protect school breaks, holidays, travel windows, and relationship time.' },
			],
		},
	},
	parentingPlanLanguage: {
		title: 'Sample 70/30 Parenting Plan Language',
		description: 'This sample is written for educational planning and should be tailored to the actual custody order, state law, and family logistics.',
		clause: 'The child will have a primary residence with Parent A for school-week and routine purposes. Parent B will have parenting time according to the following 70/30 parenting-time schedule: [describe recurring overnights, exchange days, and exchange times]. Holiday, school-break, vacation, birthday, Mother’s Day, Father’s Day, and other special-day provisions will override the regular schedule when they apply. The parents will define transportation responsibilities, exchange locations, school communication, activity participation, healthcare and childcare expense handling, and review points for revisiting the schedule as the child’s needs, school location, parent work schedules, or travel distance change.',
		disclaimer: 'This sample is educational only. Have any 70/30 parenting plan language reviewed by a qualified family law professional before filing or signing.',
	},
	deepDiveSections: [
		{
			id: 'primary-parent-responsibilities',
			kicker: 'Primary parent',
			title: 'Primary Parent Responsibilities in a 70/30 Arrangement',
			paragraphs: [
				'In a 70/30 schedule, the majority-time parent often carries more weekday responsibility. That can include school communication, appointments, transportation, activity management, homework oversight, bedtime consistency, and daily routine decisions.',
				'The plan should make these duties visible instead of assuming they happen automatically. It should also protect the other parent’s ability to receive updates and participate in school and activities.',
			],
			items: [
				{ title: 'School communication', description: 'Both parents should have access to school portals, calendars, teacher communication, and emergency updates.' },
				{ title: 'Appointments', description: 'The primary parent may schedule more appointments, but notice and cost-sharing expectations should be clear.' },
				{ title: 'Activity management', description: 'Sports, tutoring, lessons, and clubs need transportation and fee rules.' },
				{ title: 'Routine consistency', description: 'Homework, sleep, meals, medication, and morning routines should be stable without excluding the other parent.' },
			],
		},
		{
			id: 'transportation-logistics',
			kicker: 'Logistics',
			title: 'Transportation and Exchange Planning',
			paragraphs: [
				'Transportation can determine whether 70/30 works. If the primary home was chosen because it is closer to school or activities, the plan should not leave driving duties vague.',
				'Parents should define pickup responsibilities, school exchanges, weekend handoffs, long-distance arrangements, travel cost sharing, and conflict-reduction steps before the first missed pickup creates tension.',
			],
			items: [
				{ title: 'Pickup responsibilities', description: 'State whether the receiving parent picks up, the ending parent drops off, or duties alternate.' },
				{ title: 'School exchanges', description: 'School-based exchanges can reduce conflict and keep the child out of adult tension.' },
				{ title: 'Weekend exchanges', description: 'Weekend handoffs should account for practices, games, travel, and parent work shifts.' },
				{ title: 'Long-distance arrangements', description: 'Define midpoint locations, travel windows, delay notice, and expense sharing.' },
			],
		},
	],
	faq: [
		{ question: 'What is a 70/30 custody schedule?', answer: 'A 70/30 custody schedule is a parenting-time arrangement where one parent has about 70% of overnights and the other parent has about 30%. It is often used when one home anchors school routines while the other parent has predictable recurring time.' },
		{ question: 'Is 70/30 considered joint custody?', answer: 'It can be part of a joint custody or shared parenting arrangement, but legal labels vary. The percentage describes parenting time, not necessarily legal decision-making, school enrollment, medical authority, or court terminology.' },
		{ question: 'Does 70/30 affect child support?', answer: 'It can. Parenting time is only one factor used in support calculations, but a 70/30 split may be treated differently than 50/50 or 60/40 because one parent has substantially more overnights. Income, state guidelines, healthcare, childcare, and expenses can also matter.' },
		{ question: 'Which parent has primary custody in a 70/30 schedule?', answer: 'The parent with about 70% of overnights is often the primary residential parent for practical routines, but legal wording depends on the parenting plan or court order. The plan should define school, transportation, communication, and decision-making duties clearly.' },
		{ question: 'Is 70/30 better than 60/40?', answer: '70/30 may be better when 60/40 still creates too many exchanges, too much travel, or unclear school-week responsibility. 60/40 may be better when both parents can support substantial weekday time and the child benefits from a more balanced split.' },
		{ question: 'Is 70/30 better than 80/20?', answer: '70/30 may be better when the lower-time parent can handle more regular overnights than an 80/20 schedule allows. 80/20 may be more realistic when distance, work, or child needs require a stronger primary-home structure.' },
		{ question: 'Can 70/30 work for teenagers?', answer: 'Yes, especially when teen schedules include jobs, sports, driving, exams, and social plans that make frequent exchanges difficult. The plan should still protect meaningful time and avoid making the teen manage parent communication.' },
		{ question: 'Can 70/30 work for young children?', answer: 'It can work for young children when the primary-home routine is stable and the other parent has frequent, predictable contact. Long gaps can be harder for some young children, so calls, short visits, or consistent blocks may be important.' },
		{ question: 'How many overnights is 70/30 custody?', answer: 'A rough 70/30 split is about 256 overnights for one parent and 109 overnights for the other parent in a 365-day year. The exact annual total can change after holidays, school breaks, summer, and custom changes are added.' },
		{ question: 'Can parents customize 70/30?', answer: 'Yes. Parents can customize exchange days, weekends, weekday overnights, school breaks, holidays, summer blocks, transportation, and make-up time. After changes are added, use a custody percentage calculator to check the annual overnight total.' },
		{ question: 'How do holidays work in 70/30 custody?', answer: 'Holiday rules usually override the regular schedule. In 70/30 plans, holidays can also help preserve the lower-time parent relationship by providing meaningful tradition time, travel windows, and school-break overnights.' },
		{ question: 'How do vacations work in a 70/30 arrangement?', answer: 'Vacation rules should define notice, trip length, travel details, passports if relevant, missed regular time, and whether vacation overnights count toward the annual split. Longer vacation blocks may be especially important for the 30% parent.' },
		{ question: 'Can 70/30 change later?', answer: 'Yes. Families may move from 70/30 toward 60/40 or 50/50 if distance, school, work, or child needs change. They may also move toward 80/20 if travel, availability, or school logistics become harder. Review points should be written down.' },
		{ question: 'What if parents live far apart?', answer: '70/30 can be a practical option when parents live far enough apart that frequent school-week exchanges are stressful. The plan should define transportation duties, travel costs, exchange locations, and long-distance backup rules.' },
		{ question: 'Is 70/30 common?', answer: '70/30 is common as a middle-primary arrangement: more structured than 60/40, but usually more parenting time than a basic every-other-weekend plan. Families use it when one home needs to anchor school routines while the other parent remains consistently involved.' },
		{ question: 'How do schools handle 70/30 families?', answer: 'Schools usually need clear contact information, pickup authorization, portal access, emergency contacts, and communication preferences. Both parents should receive school information unless a court order says otherwise.' },
		{ question: 'What should be written into a 70/30 parenting plan?', answer: 'A 70/30 plan should define primary residence, exact overnights, exchange times, transportation duties, holiday overrides, vacations, school communication, activity costs, healthcare and childcare expense handling, and review points.' },
		{ question: 'What is the biggest risk in a 70/30 schedule?', answer: 'The biggest risk is letting the percentage replace the actual parenting plan. A strong 70/30 arrangement must explain responsibilities, protect the lower-time parent relationship, and keep school, transportation, support, and holidays clear.' },
	],
	relatedSchedules: [
		'60-40-custody-schedule',
		'80-20-custody-schedule',
		'50-50-custody-schedule',
		'every-other-weekend-custody-schedule',
	],
	relatedTools: [
		{ title: 'Child support calculator', slug: 'texas-child-support-calculator', description: 'Estimate support after reviewing parenting time, income, and expenses.' },
		{ title: 'Custody percentage calculator', slug: 'custody-percentage-calculator', description: 'Estimate annual parenting time percentages from overnight totals.' },
		{ title: 'Parenting time calculator', slug: 'custody-percentage-calculator', description: 'Compare parenting time totals across nearby custody percentages.' },
		{ title: 'Parenting plan template', slug: 'parenting-plan-template', description: 'Document primary residence, exchanges, holidays, and responsibilities.' },
	],
	relatedHeading: 'Related 70/30 planning tools and comparisons',
	relatedLinks: [
		{ title: '60/40 Custody Schedule', slug: '60-40-custody-schedule', description: 'Compare 70/30 with a less primary-home parenting-time split.' },
		{ title: '80/20 Custody Schedule', slug: '80-20-custody-schedule', description: 'Compare 70/30 with a stronger primary-home arrangement.' },
		{ title: '50/50 Custody Schedule', slug: '50-50-custody-schedule', description: 'Review when equal parenting time may or may not be realistic.' },
		{ title: 'Every Other Weekend Custody Schedule', slug: 'every-other-weekend-custody-schedule', description: 'Compare 70/30 with a more traditional weekend-focused plan.' },
		{ title: 'Child Support Calculator', slug: 'texas-child-support-calculator', description: 'Review support planning after considering parenting time and expenses.' },
		{ title: 'Custody Percentage Calculator', slug: 'custody-percentage-calculator', description: 'Check annual overnights after holidays, breaks, and custom changes.' },
		{ title: 'Parenting Time Calculator', slug: 'custody-percentage-calculator', description: 'Compare nearby parenting-time allocations before finalizing terms.' },
		{ title: 'Holiday Custody Planner', slug: 'holiday-custody-schedule', description: 'Plan holidays, school breaks, vacations, and travel windows separately.' },
	],
	article: {
		headline: 'The Complete Guide to 70/30 Custody',
		authorName: 'CustodyBuilder Editorial Team',
		reviewerName: 'CustodyBuilder Editorial Team',
		datePublished: '2026-06-13',
		dateModified: '2026-06-13',
	},
};

export default schedule;
